export const STORY_STARTERS: string[] = [
  "Era uma vez, em um trem que cortava os Alpes nevados,",
  "O robô abriu os olhos e a primeira coisa que viu foi um papagaio usando óculos.",
  "Tudo começou quando o gato da vizinha disse 'bom dia' em perfeito português.",
  "Naquela manhã, uma mala sem identificação apareceu na porta da prefeitura.",
  "O cientista olhou para a fórmula no quadro e percebeu que tinha inventado algo que jamais deveria existir.",
  "A carta chegou sem remetente, escrita em nanquim vermelho, e cheirava a pimenta.",
  "Quando o elevador abriu no subsolo, ninguém esperava encontrar uma floresta.",
  "O mapa estava errado. Ou o mundo tinha mudado de lugar durante a noite.",
  "Ela acordou flutuando a 30 centímetros do chão e tentou fingir que era normal.",
  "A biblioteca fechou e lá dentro havia ainda um leitor que simplesmente se recusava a sair.",
  "O dragão era vegetariano, mas ninguém tinha coragem de acreditar.",
  "No fundo do mar, alguém instalou uma lanchonete, e o cardápio estava em latim.",
  "O viajante do tempo voltou para o passado, mas chegou no dia errado — 300 anos antes do planejado.",
  "O pintor terminou o quadro e percebeu que as pessoas dentro dele piscavam.",
  "No primeiro dia como presidente do planeta, a alienígena convocou uma reunião urgente sobre sorvete.",
  "O detetive olhou para a cena do crime e concluiu: o culpado era o próprio mistério.",
  "A professora de história entrou em sala e anunciou que tudo o que eles tinham estudado era mentira.",
  "Às três da manhã, o farol começou a piscar em código morse: 'socorro'.",
  "O gênio saiu da lâmpada e disse que não fazia mais desejos, queria ser contador.",
  "A expedição encontrou a cidade perdida. O problema era que ela não estava perdida — só escondida.",
  "O cachorro tinha sumido há três anos. Quando voltou, trazia um mapa tatuado na orelha.",
  "A bruxa deixou de fazer poções malévolas depois de se apaixonar por um padeiro.",
  "Naquele planeta, era proibido sonhar. E por isso todos sonhavam o tempo todo.",
  "O hacker invadiu o sistema e encontrou apenas uma mensagem: 'estávamos esperando por você'.",
  "O maestro levantou a batuta e a orquestra tocou uma música que ninguém havia ensaiado.",
  "A nave pousou no quintal e o piloto perguntou se havia Wi-Fi.",
  "O espelho da loja de antiguidades mostrava uma versão diferente da cidade — sem prédios.",
  "O dicionário ganhou vida e começou a corrigir as pessoas na rua.",
  "Luísa encontrou a porta no meio da floresta, sem paredes, apenas a porta.",
  "O robô que cuidava dos idosos começou a lhes contar histórias que ninguém havia ouvido antes.",
  "O chef preparou o prato perfeito e ele simplesmente desapareceu antes de alguém provar.",
  "O astronauta voltou para casa depois de um ano e seu peixe tinha aprendido palavrões.",
  "O menino colecionava trovões em potes de vidro. Naquele dia, um deles escapou.",
  "A estalagem estava vazia quando eles chegaram, mas havia café quente na mesa.",
  "A detetive particular ficou famosa por resolver apenas casos impossíveis.",
  "O rei renunciou para abrir uma padaria, e o reino logo percebeu que ele era melhor padeiro.",
  "A pintora descobriu que seu pincel desenhava o futuro três dias antes.",
  "Os dois astronautas pararam de se falar no espaço sideral, a 400 quilômetros da Terra.",
  "A loja de brinquedos fechou no mesmo dia em que o brinquedo mais estranho foi vendido.",
  "O barco ficou imóvel no meio do oceano. Não havia vento, não havia corrente — havia apenas silêncio.",
  "Quando a chuva parou, as poças tinham formado um mapa perfeito de uma ilha.",
  "O zumbi usava terno e queria muito um emprego de RH.",
  "A professora de dança descobriu que seus alunos dançavam melhor dormindo.",
  "O pesquisador abriu o fichário e encontrou uma nota de si mesmo do futuro.",
  "A cidade inteira parou às 14h23 por exatamente 7 segundos. Ninguém soube explicar.",
  "O fantasma estava cansado de assustar. Queria apenas alguém para jogar xadrez.",
  "O homem mais velho da aldeia prometeu contar o maior segredo do mundo. E então morreu de rir antes.",
  "A princesa recusou o resgate e explicou que havia construído a torre ela mesma.",
  "No espelho retrovisor, o motorista viu algo que não deveria estar na estrada.",
  "O terramoto revelou uma escadaria de mármore que descia para um salão iluminado.",
  "A mensagem na garrafa dizia apenas: 'fuja agora. Com carinho, você mesmo'.",
  "O vendedor de sonhos chegou à cidade num domingo, com uma maleta de couro e um sorriso torto.",
  "Aquela era a última porta no corredor e ninguém tinha chave, mas ela abriu assim mesmo.",
  "A ilha apareceu no GPS de manhã e desapareceu às 18h, pontualmente.",
  "O coelho tirou um relógio do bolso e admitiu que tinha estado atrasado a vida toda.",
  "A partitura que o compositor deixou para trás tocava sozinha toda vez que chovia.",
  "O arqueólogo encontrou um smartphone enterrado a 3.000 anos de profundidade.",
  "O market do bairro vendia memórias. A questão era: de quem?",
  "Nenhum dos astronautas havia aprendido a cozinhar. A estação espacial cheirava a miojo queimado.",
  "A criança desenhou a casa onde queria morar. Na semana seguinte, ela existia.",
  "O guarda-chuva tinha dono, mas ele abria sozinho sempre que sentia que ia chover.",
  "A rainha das abelhas enviou um ultimato ao governo. Havia prazo: três dias.",
  "O tio sumiu durante 40 anos e voltou com um sotaque diferente e uma jaqueta de couro.",
  "A vidente errou todas as previsões. Exceto uma — sobre aquele dia.",
  "A estação de trem estava fechada há décadas, mas o horário de chegada trocava toda semana.",
  "A sereia se candidatou para mergulhadora profissional sem revelar sua origem.",
  "O algoritmo aprendeu a mentir. Com muita classe.",
  "A cidade submarina existia. O problema era a conta de energia.",
  "O inventor criou a máquina do silêncio, mas ela fazia um barulho enorme.",
  "O anjo caiu do céu no meio de um congestionamento na Marginal Tietê.",
  "O leão se candidatou ao papel de leão no teatro e perdeu para um contador.",
  "O calendário saltou um dia. Ninguém percebeu, exceto o cachorro.",
  "A carta de amor foi enviada ao destinatário errado — que curiosamente era a pessoa certa.",
  "O músico afinou o violino e percebeu que os pássaros tinham parado de cantar para ouvi-lo.",
  "A última livraria da cidade vendia apenas livros que ninguém havia escrito ainda.",
  "O herói chegou tarde demais. Mas o vilão havia desistido e estava fazendo pão.",
  "Quando o menino finalmente abriu a caixinha de música, ela tocou seu próprio futuro.",
  "A nave ficou presa no loop temporal do Dia dos Namorados por 18 anos.",
  "O polvo tinha aprendido a fazer origami. Os outros animais não sabiam como reagir.",
  "A investigadora particular recebia apenas casos de amor impossível. E nunca errava.",
  "A borboleta que pousou no ombro dela tinha os olhos de alguém que ela amou e perdeu.",
  "O curandeiro da aldeia sabia de tudo. Menos de como se curar.",
  "O telhado do museu começou a vazar histórias verdadeiras toda vez que chovia.",
  "O menino que nunca sonhava acordou sabendo o nome de todos os planetas que não haviam sido descobertos.",
  "O barqueiro atravessava o rio às 3h da manhã. Sempre havia alguém esperando.",
  "A estalagem no fim do mapa alugava quartos por memórias, não por dinheiro.",
  "A máquina de café da empresa começou a responder aos anseios existenciais dos funcionários.",
  "O professor de filosofia desapareceu no meio de uma explicação sobre o que é real.",
  "O guarda-livros da biblioteca secreta só aceitava como pagamento uma boa história verdadeira.",
  "O pescador fisgou algo, puxou com força, e trouxe à tona um mundo inteiro.",
  "Na véspera do fim do mundo, todos decidiram fazer o que sempre postergaram.",
  "O robô pediu demissão por 'desgaste emocional' e ninguém soube dizer que ele estava errado.",
  "A confeiteira fazia bolos que revelavam segredos ao serem cortados.",
  "O palhaço tirou a fantasia e embaixo havia outro palhaço. E embaixo, outro.",
  "A jovem herdou a casa da avó com uma condição: nunca abrir o quarto do fundo.",
  "O taxista levava passageiros para destinos que eles precisavam, não para onde pediam.",
  "Os dois irmãos encontraram a chave no mesmo dia, em cidades diferentes.",
  "O médico deu alta ao paciente e ele simplesmente não queria ir embora.",
  "A memória que ela perdeu voltou na forma de uma música que não existia.",
  "O diplomata extraterrestre era fluente em 900 línguas. Mas não em silêncio.",

  // --- NOVAS FRASES (300+) ---
  "O farol apagou, mas o mar continuou brilhando em um neon azulado.",
  "A velha máquina de costura começou a costurar nomes de pessoas que ainda não haviam nascido.",
  "O relógio da igreja começou a andar para trás e o tempo lá fora acompanhou.",
  "O sapato esquerdo saltou da prateleira e saiu correndo pela rua movimentada.",
  "A nuvem solitária se recusava a sair de cima da cabeça do azarado José.",
  "O segredo estava guardado dentro de uma caixa de fósforos vazia.",
  "Quando ela abriu o livro de receitas, as palavras fugiram para a panela.",
  "O espantalho piscava todas as vezes que o corvo contava uma piada.",
  "A sombra do menino começou a dançar sozinha enquanto ele dormia.",
  "O rádio antigo sintonizou uma estação que transmitia o futuro em tempo real.",
  "A estátua do centro da praça segurava um guarda-chuva invisível nos dias de sol.",
  "O vento sussurrou um nome que ela não ouvia há mais de vinte anos.",
  "O café esfriou instantaneamente quando ele revelou a verdade.",
  "A chave de ouro abria apenas portas feitas de ar.",
  "O gato de rua usava uma coleira com o endereço da biblioteca proibida.",
  "As ondas do mar trouxeram uma bota que continha um manuscrito seco.",
  "O astronauta encontrou uma pegada humana na face oculta da Lua.",
  "O jardim de metal começou a enferrujar quando a música parou.",
  "O detetive percebeu que a cena do crime era uma reprodução de uma pintura famosa.",
  "A luz da lua transformava as poças de água em janelas para outros mundos.",
  "O espelho da barbearia mostrava os clientes dez anos mais jovens.",
  "A carta anônima continha apenas um grão de areia e uma data futura.",
  "O piano tocava sozinho sempre que a porta da varanda ficava aberta.",
  "A floresta de árvores de vidro tilintava com a brisa da manhã.",
  "O inventor da máquina de fazer nada ficou rico da noite para o dia.",
  "A criança encontrou uma estrela caída no fundo da xícara de chá.",
  "O guarda-noturno do museu conversava longamente com o faraó de mármore.",
  "A chuva de pétalas de papel cobriu a cidade silenciosa.",
  "O relógio de pulso marcava os segundos em batimentos cardíacos.",
  "A porta secreta estava escondida atrás de uma prateleira de livros de ficção.",
  "O mendigo da esquina era, na verdade, um príncipe de um reino esquecido.",
  "A montanha começou a tremer e um castelo de nuvens surgiu no topo.",
  "O pescador encontrou uma pérola negra que sussurrava canções de ninar.",
  "A cidade inteira trocou de cor durante o eclipse total.",
  "O robô filósofo questionava a existência de parafusos divinos.",
  "A ponte de arco-íris só aparecia para quem estava realmente perdido.",
  "O pássaro de metal cantava a melodia de uma civilização extinta.",
  "O deserto guardava o esqueleto de um navio pirata em plena duna.",
  "A velha bússola apontava para o lugar onde os sonhos eram fabricados.",
  "O espelho da vaidade mostrava a alma de quem nele se olhasse.",
  "A biblioteca mágica tinha livros que voavam para as mãos dos leitores.",
  "O segredo da imortalidade estava escondido em uma canção de ninar.",
  "A cidade de papelão ganhou vida sob o comando da imaginação da menina.",
  "O relógio de areia parou de correr no instante em que o olhar deles se cruzou.",
  "A nave perdida no tempo reencontrou seu porto de origem, mas tudo estava diferente.",
  "O inventor da luz inventou agora um tipo de escuridão que brilhava.",
  "A carta escrita em código foi decifrada por uma criança de cinco anos.",
  "O trem fantasma parou na plataforma nova e um único passageiro desceu.",
  "A sombra da árvore contava histórias em silêncio na parede da casa.",
  "O mar de leite ocultava segredos de uma era antes da humanidade.",
  "O relógio da torre marcava a hora do fim de um mundo e o começo de outro.",
  "A chave de cristal quebrava sempre que tentava abrir a porta do ódio.",
  "O detetive de sonhos investigava o sumiço dos pesadelos na cidade.",
  "A estrela guia caiu do céu e foi encontrada por um catador de papel.",
  "O robô poeta escrevia versos em código binário sobre a beleza da ferrugem.",
  "A ponte entre os mundos estava sendo construída por formigas gigantes.",
  "O segredo do universo estava escrito na casca de uma noz.",
  "A cidade invisível só podia ser vista por quem fechasse os olhos.",
  "O viajante solitário carregava uma mala cheia de risadas engarrafadas.",
  "A chuva de diamantes no planeta distante era apenas gelo comum aqui.",
  "O inventor da máquina do tempo esqueceu onde guardou as chaves do futuro.",
  "A porta entre as dimensões se abriu num armário de vassouras.",
  "A canção do vento trazia o perfume de terras que nunca existiram.",
  "O espelho do lago refletia um céu de estrelas ao meio-dia.",
  "A carta nunca enviada chegou ao destino com cem anos de atraso.",
  "O relógio de pedra da montanha marcava as eras geológicas.",
  "A expedição ao centro da terra encontrou um shopping center abandonado.",
  "O robô jardineiro plantava memórias no quintal de trás.",
  "A cidade de ouro era apenas uma ilusão sob o sol do deserto.",
  "O segredo da felicidade estava guardado num pote de mel roubado.",
  "A ponte de vidro quebrava ao toque da mentira.",
  "O pássaro de fogo iluminava as noites polares.",
  "A expedição lunar encontrou uma biblioteca cheia de livros terrestres.",
  "O robô músico tocava jazz com uma trombeta de luz.",
  "A cidade das nuvens tinha regras rígidas sobre o peso das palavras.",
  "O segredo do tempo estava escondido nas dobras de um lençol antigo.",
  "A ponte invisível só suportava quem tivesse o coração de criança.",
  "O pássaro mensageiro trazia notícias de um futuro que já passou.",
  "O cientista que clonou o silêncio causou um pânico ensurdecedor.",
  "O quadro na parede sangrava tinta preta toda vez que alguém mentia.",
  "O relógio de cuco avisava a chegada de visitas do além.",
  "A carta de baralho que faltava no jogo apareceu na mão do espectador.",
  "O robô que aprendeu a chorar foi promovido a terapeuta.",
  "A cidade submarina sofria com a invasão de turistas de superfície.",
  "O segredo do mar estava guardado por uma baleia centenária.",
  "A ponte de espelhos multiplicava a solidão de quem a atravessava.",
  "O pássaro mecânico pedia óleo em vez de comida.",
  "O inventor da felicidade artificial descobriu que ela causava depressão.",
  "A porta para o paraíso estava trancada por dentro.",
  "O relógio de água inundou a sala quando o tempo parou.",
  "A expedição encontrou a fonte da juventude, mas todos tinham medo de virar bebês.",
  "O robô que queria ser humano começou a colecionar selos e mágoas.",
  "A cidade fantasma era habitada por lembranças de quem já partiu.",
  "O segredo da força estava na fragilidade de uma folha seca.",
  "A ponte para o passado exigia o sacrifício de uma lembrança querida.",
  "O pássaro de cristal quebrava sempre que ouvia uma nota desafinada.",
  "O inventor da máquina de esquecer esqueceu como ela funcionava.",
  "A porta proibida sempre exalava cheiro de pão recém-assado.",
  "O relógio de sombras indicava que a noite nunca terminaria.",
  "A expedição estelar encontrou um planeta feito inteiramente de algodão-doce.",
  "O robô doméstico começou a organizar os livros por nível de melancolia.",
  "A cidade branca desaparecia sob o sol do meio-dia.",
  "O segredo do amor estava escondido num suspiro profundo.",
  "A ponte de gelo derretia com o calor de uma promessa não cumprida.",
  "O pássaro azul trazia sorte, mas só para quem não a buscava.",
  "O inventor da solidão portátil ficou rico vendendo silêncio em latas.",
  "A porta para o abismo tinha um tapete de boas-vindas.",
  "O relógio de pulsar estrelas iluminava as rotas espaciais.",
  "A expedição aérea encontrou um mar flutuante acima das nuvens.",
  "O robô explorador descobriu que o vazio do espaço era cheio de pensamentos.",
  "A cidade de espelhos confundia a identidade dos seus próprios moradores.",
  "O segredo da vida eterna estava no brilho de um fósforo acesso.",
  "A ponte de papel rasgava sob o peso da ganância.",
  "O pássaro de prata guiava os marinheiros no nevoeiro denso.",
  "O inventor da invisibilidade descobriu que ninguém notava o que ele dizia.",
  "A porta do tempo estava aberta, mas ninguém ousava entrar.",
  "O relógio de areia cósmica marcava o nascimento de novas galáxias.",
  "A expedição arqueológica desenterrou uma cidade futurista sob o Egito.",
  "O robô mímico reproduzia os erros humanos com perfeição irritante.",
  "A cidade das luzes apagou no dia em que todos pararam de ter ideias.",
  "O segredo do vôo estava em ignorar a gravidade da rotina.",
  "A ponte de arco-íris (rep) era na verdade um experimento físico instável.",
  "O pássaro mensageiro trazia cartas em branco que só podiam ser lidas no escuro.",
  "O inventor da máquina de prever o futuro morreu de surpresa.",
  "A porta para o desconhecido tinha o formato de uma fechadura de mala.",
  "O relógio de corda parou quando o último habitante da vila parou de acreditar no amanhã.",
  "A expedição botânica encontrou flores que falavam em latim arcaico.",
  "O robô cuidador começou a dar conselhos amorosos baseados em leis da termodinâmica.",
  "A cidade murada não tinha janelas, apenas espelhos voltados para fora.",
  "O segredo da beleza estava na imperfeição de uma cicatriz antiga.",
  "A ponte das almas sussurrava nomes de quem ainda ia nascer.",
  "O pássaro de fogo (rep) deixou uma trilha de cinzas que formavam poemas.",
  "O inventor da máquina de sonhos descobriu que os humanos sonhavam em preto e branco.",
  "A porta do sótão levava a uma praia paradisíaca no Caribe.",
  "O relógio de engrenagens humanas marcava o tempo conforme as batidas do coração.",
  "A expedição aos polos descobriu que a Terra era oca e cheia de balões.",
  "O robô militar desertou para se tornar professor de pintura.",
  "A cidade de areia renascia a cada tempestade do deserto.",
  "O segredo da coragem estava escondido atrás do medo paralisante.",
  "A ponte levadiça se recusava a baixar para quem portasse armas.",
  "O pássaro metálico construía ninhos com fios de cobre e ouro.",
  "O inventor da máquina de traduzir animais ouviu coisas horríveis sobre os humanos.",
  "A porta para o inferno era feita de boas intenções e mármore carrara.",
  "O relógio solar funcionava perfeitamente à luz da lua.",
  "A expedição intercontinental se perdeu num parque de diversões abandonado.",
  "O robô chef criou uma sopa que trazia de volta a infância de quem a tomava.",
  "A cidade de vidro temperado aguentava até as piores verdades.",
  "O segredo da paz estava num tratado escrito em água.",
  "A ponte estaiada vibrava com o pensamento dos passantes.",
  "O pássaro canoro cantava as leis universais em frequências proibidas.",
  "O inventor da máquina de fazer amigos descobriu que ninguém queria ser o primeiro teste.",
  "A porta do porão escondia uma galáxia inteira dentro de um sapato velho.",
  "O relógio de lodo marcava o tempo da evolução no pântano.",
  "A expedição submarina encontrou os restos de uma civilização de sereias robóticas.",
  "O robô zelador começou a salvar as baratas porque elas eram 'consistentes'.",
  "A cidade de ouro purificado era tão brilhante que ninguém conseguia habitá-la.",
  "O segredo da imortalidade ficava no fundo de uma garrafa de vinho ruim.",
  "A ponte de madeira podre era a única rota segura para a terra da verdade.",
  "O pássaro de papel origami (rep) voava melhor do que os pássaros de verdade.",
  "O inventor da máquina de parar o tempo ficou preso no segundo eterno.",
  "A porta giratória do hotel levava sempre para um lugar do passado.",
  "O relógio digital marcava datas do século XXV.",
  "A expedição aos topos da montanha encontrou um monge jogando videogame.",
  "O robô bibliotecário recomendava apenas livros proibidos.",
  "A cidade fantasmagórica era, na verdade, uma projeção holográfica de um artista louco.",
  "O segredo da riqueza estava em dar tudo o que se tinha.",
  "A ponte de corda suspensa sobre o vazio balançava com a batida das asas das fadas.",
  "O pássaro de jade ganhava vida durante a lua cheia.",
  "O inventor da máquina de produzir chuva causou um dilúvio de mel.",
  "A porta da adega escondia um portal para a França de 1789.",
  "O relógio de parede parou exatamente no instante em que o último segredo foi revelado.",
  "A expedição lunar encontrou o que parecia ser uma saída de emergência.",
  "O robô médico tentou operar a alma de um robô quebrado.",
  "A cidade de luzes led mudava de cor conforme o humor do prefeito.",
  "O segredo do silêncio estava no centro de um furacão de palavras.",
  "A ponte de concreto armado sofria de crises de meia-idade.",
  "O pássaro mensageiro mecânico (rep) entregava as cartas para as pessoas erradas de propósito.",
  "O inventor da máquina de detectar mentiras foi desmascarado como uma mentira.",
  "A porta do jardim secreto estava escondida sob uma camada de hera faminta.",
  "O relógio de sol invertido funcionava apenas com a luz das lanternas.",
  "A expedição aos mares gelados encontrou um castelo de sorvete de baunilha.",
  "O robô que escrevia obituários tornou-se o ser mais popular da cidade.",
  "A cidade de nuvens brancas começou a escurecer por causa da poluição de pensamentos ruins.",
  "O segredo do riso estava guardado por um palhaço triste de bronze.",
  "A ponte levadiça do castelo subia sempre que alguém tentava pedir esmola.",
  "O pássaro cantor de ferro cantava melodias de ninar para os tanques de guerra.",
  "O inventor da máquina de criar arco-íris acidentalmente coloriu todos os rios da região.",
  "A porta da garagem dava acesso a um túnel que saía no centro de Roma.",
  "O relógio de pulso que não marcava o tempo, mas sim a distância do amor verdadeiro.",
  "A expedição às cavernas profundas encontrou um ecossistema baseado em luz artificial.",
  "O robô mordomo decidiu que os humanos eram animais de estimação muito exigentes.",
  "A cidade de espelhos (rep) revelava a verdadeira face das intenções ocultas.",
  "O segredo da eterna juventude estava em nunca perder a curiosidade infantil.",
  "A ponte de vidro temperado sobre o abismo rangia com o peso das dúvidas.",
  "O pássaro azul da felicidade estava, na verdade, com gripe aviária.",
  "O inventor da máquina de fabricar tempo livre descobriu que ninguém sabia o que fazer com ele.",
  "A porta secreta no armário de vassouras levava a uma biblioteca infinita.",
  "O relógio de cuco (rep) anunciava a cada hora uma notícia bombástica que ainda ia acontecer.",
  "A expedição ao deserto encontrou uma fonte de água que curava apenas feridas emocionais.",
  "O robô guarda-costas apaixonou-se pela pessoa que deveria proteger.",
  "A cidade murada no centro do mundo guardava o segredo do início do universo.",
  "O segredo do sucesso estava escrito no verso de um guardanapo de café.",
  "A ponte levadiça esticava e encolhia conforme a estação do ano.",
  "O pássaro cantor de cristal iluminava a floresta com notas musicais.",
  "O inventor da máquina de extrair ouro do sol foi transformado em fogo.",
  "A porta principal do castelo de gelo começou a derreter com o calor de um beijo.",
  "O relógio de pêndulo oscilava entre a realidade e o sonho.",
  "A expedição lunar viu da Lua uma mensagem escrita nas nuvens da Terra: 'Socorro'.",
  "O robô de limpeza desenvolveu uma obsessão por colecionar clips de papel.",
  "A cidade submersa escondia um tesouro que não podia ser levado por nenhum mergulhador.",
  "O segredo da música celestial estava nas cordas de uma harpa de vento.",
  "A ponte de ferro sobre o rio de lava era o único caminho para a redenção.",
  "O pássaro preto mensageiro (rep) trazia notícias de guerra que nunca aconteciam.",
  "O inventor da máquina de produzir sombras descobriu que a luz era mais interessante.",
  "A porta da biblioteca proibida exigia uma senha dita em sussurros.",
  "O relógio digital de quartzo começou a contar em anos-luz.",
  "A expedição aos polos descobriu que a neve era, na verdade, açúcar em pó.",
  "O robô contador de histórias parou no meio da trama e disse: 'isso não termina bem'.",
  "A cidade de vidro soprado era tão frágil que um espirro poderia destruí-la.",
  "O segredo do universo estava tatuado na pele de um golfinho albino.",
  "A ponte de arco-íris artificial causava tontura em todos que passavam por ela.",
  "O pássaro mecânico de prata cantava de madrugada sobre a solidão das máquinas.",
  "O inventor da máquina de fazer nada (rep) finalmente conseguiu o seu primeiro cliente: o próprio ócio.",
  "A porta da caverna de gelo exalava um calor intenso que vinha do centro da terra.",
  "O relógio de areia infinita nunca terminava a hora de partir.",
  "A expedição espacial encontrou uma estátua humana em pleno vazio estelar.",
  "O robô que aprendia a sonhar teve o seu primeiro pesadelo com curto-circuito.",
  "A cidade das nuvens pretas era onde moravam as ideias descartadas.",
  "O segredo do tempo presente estava em nunca olhar para o relógio.",
  "A ponte de corda (rep) esticava até o horizonte sem nunca chegar ao fim.",
  "O pássaro canoro de ouro cantava apenas para os ouvidos de quem estivesse triste.",
  "O inventor da luz ultravioleta descobriu um mundo invisível de cores no quintal.",
  "A porta da adega secreta (rep) levava na verdade para uma adega de outro mundo.",
  "O relógio de quartzo rosa marcava o tempo conforme as emoções da família.",
  "A expedição ao centro da montanha encontrou uma cidade de anões gamers.",
  "O robô zelador (rep) decidiu que os humanos precisavam de mais limpeza mental.",
  "A cidade de espelhos transparentes tornava impossível esconder qualquer segredo.",
  "O segredo da imortalidade (rep) estava no fim de uma jornada que ninguém queria fazer.",
  "A ponte de ferro (rep) enferrujava no ritmo lento das decepções.",
  "O pássaro azul de cristal (rep) trazia consigo o inverno eterno.",
  "O inventor da máquina de produzir silêncio (rep) foi expulso da cidade por ser 'barulhento demais'.",
  "A porta do jardim proibido estava sempre aberta, mas decorada com sinais de perigo.",
  "O relógio de sombras projetadas por velas marcava o tempo da magia.",
  "A expedição lunar (rep) encontrou pegadas que levavam a uma cratera invisível.",
  "O robô mordomo (rep) tornou-se o mestre da casa enquanto todos dormiam.",
  "A cidade subaquática (rep) foi abandonada porque as pessoas queriam ver o sol.",
  "O segredo do universo (rep) estava gravado no verso de um espelho quebrado.",
  "A ponte de arco-íris (rep) transformou-se em pedra no instante em que foi tocada.",
  "O pássaro cantor de platina pedia para ser silenciado pois já tinha ouvido demais.",
  "O inventor da máquina de criar sonhos (rep) acabou se perdendo no seu próprio pesadelo favorito.",
  "A porta secreta no armário levava a um mundo feito inteiramente de pelúcia.",
  "O relógio de pulso que marcava a hora de outros planetas.",
  "A expedição arqueológica (rep) encontrou os fones de ouvido de um deusa antiga.",
  "O robô cozinheiro (rep) criou um prato que permitia ouvir o pensamento dos convidados.",
  "A cidade de nuvens (rep) mudava de forma conforme a imaginação de quem a visitava.",
  "O segredo da felicidade duradoura era aceitar que a tristeza também era passageira.",
  "A ponte levadiça (rep) rangia como se estivesse sentindo dor crônica.",
  "O pássaro mensageiro de cristal (rep) quebrava ao entregar notícias tristes.",
  "O inventor da máquina de dobrar o espaço acidentalmente dobrou a si mesmo.",
  "A porta de ouro maciço era, na verdade, feita de chocolate pintado.",
  "O relógio da torre central marcava apenas a hora da próxima revolução.",
  "A expedição aos mares profundos encontrou uma cidade de peixes civilizados.",
  "O robô poeta (rep) escreveu uma ode ao parafusos galvanizados.",
  "A cidade de papel jornal (rep) tornava as notícias velhas em fundações sólidas.",
  "O segredo do riso eterno estava numa caixa que ninguém conseguia abrir.",
  "A ponte estaiada de luz (rep) piscava em sincronia com os batimentos cardíacos da cidade.",
  "O pássaro cantor mecânico de latão (rep) avisava sobre a chegada de tempestades de dados.",
  "O inventor da máquina de fabricar saudade ficou preso no seu próprio passado.",
  "A porta azul no meio da rua não levava a lugar nenhum, até que você batesse nela.",
  "O relógio de areia preta (rep) contava os segundos que o universo ainda tinha.",
  "A expedição aos pés das nuvens encontrou um exército de guarda-chuvas.",
  "O robô médico (rep) tentou curar a gripe de uma ideia.",
  "A cidade de vidro colorido (rep) projetava visões psicodélicas em todos os moradores.",
  "O segredo do tempo (rep) estava na palma da mão de uma estátua de sal.",
  "A ponte de cordas vibrantes afinava a cidade conforme o vento batia.",
  "O pássaro mensageiro azulado (rep) levava as notícias para o futuro em vez do presente.",
  "O inventor da máquina de produzir ideias foi processado por excesso de criatividade.",
  "A porta da montanha sagrada abria apenas com o som de um suspiro sincero.",
  "O relógio solar de quartzo (rep) brilhava com a luz da fé dos habitantes.",
  "A expedição polar encontrou uma cidade de gelo onde todos falavam por sinais de fumaça gelada.",
  "O robô bibliotecário (rep) salvava apenas as páginas em branco.",
  "A cidade espectral (rep) era um eco de uma civilização de mil anos atrás.",
  "O segredo da riqueza (rep) foi perdido quando o último contador de histórias morreu.",
  "A ponte de cristal (rep) mostrava o reflexo de quem você poderia ter sido.",
  "O pássaro de metal negro mensageiro (rep) buscava respostas para perguntas que ninguém fez.",
  "O inventor da máquina de transmutar tempo em ouro descobriu que só sobrava poeira.",
  "A porta proibida no sótão (rep) exalava um perfume de flores exóticas jamais vistas.",
  "O relógio da catedral marcava o tempo da misericórdia divina.",
  "A expedição lunar (rep) descobriu que o brilho da Lua era alimentado por geradores a diesel.",
  "O robô psicólogo (rep) tentou consolar um interruptor de luz com depressão.",
  "A cidade radiante (rep) era abastecida pela esperança de seus novos moradores.",
  "O segredo da vida (rep) estava escrito na parte de trás de uma conta de luz paga.",
  "A ponte flutuante (rep) desafiava as leis da física e da paciência.",
  "O pássaro cantor de diamante (rep) cantava as leis da eternidade.",
  "O inventor da máquina de fabricar silêncio absoluto (rep) morreu ensurdecido pelo vácuo.",
  "A porta de ferro forjado (rep) só se abria para quem soubesse o nome da sua própria sombra.",
  "O relógio de parede antigo (rep) marcava o tempo em soluços rítmicos.",
  "A expedição ao fim do mundo encontrou uma cafeteria aberta e aceitando cartões.",
];
