export const ANIMAIS_POP: string[] = [
  // Mamíferos Domésticos e de Fazenda
  'Cachorro (Cão)','Gato','Cavalo','Vaca','Boi','Touro','Bezerro','Ovelha','Carneiro',
  'Cordeiro','Cabra','Bode','Cabrito','Porco','Leitão','Burro','Jumento','Mula',
  'Jegue (rep)','Coelho','Hamster','Porquinho-da-índia','Chinchila','Furão (Ferret)',
  'Rato','Camundongo','Búfalo','Zebu','Camelo','Dromedário','Lhama','Alpaca',
  // Mamíferos Selvagens (Populares)
  'Leão','Leoa','Filhote de Leão','Tigre','Leopardo','Guepardo (Chita)','Pantera Negra',
  'Onça-pintada','Onça-parda (Sussuarana)','Puma','Lince','Gato-selvagem',
  'Elefante','Rinoceronte','Hipopótamo','Girafa','Zebra','Antílope','Gazela',
  'Gnu','Hiena','Suricato','Javali','Facocero (Pumba)','Cervo (Veado)','Alce',
  'Rena (Papai Noel)','Urso Pardo','Urso Polar','Urso Panda','Panda Vermelho',
  'Urso Negro','Coala','Canguru','Wallaby','Ornitorrinco','Equidna','Diabo da Tasmânia',
  'Lobo','Coiote','Raposa','Chacal','Cão Selvagem Africano','Guaxinim','Gambá',
  'Texugo','Esquilo','Marmota','Castor','Lontra','Ariranha','Peixe-boi',
  'Morcego','Tatu','Tamanduá-bandeira','Tamanduá-mirim','Preguiça (Bicho-preguiça)',
  'Capivara','Paca','Cutia','Preá','Porco-espinho','Ouricho-caixeiro',
  // Primatas
  'Macaco','Gorila','Chimpanzé','Orangotango','Babuíno','Mico-leão-dourado',
  'Sagui','Bugio','Mandril','Lêmure (Rei Julien)','Gibão','Társio',
  // Animais Marinhos e Aquáticos
  'Baleia Azul','Baleia Jubarte','Baleia Orca (Wales)','Cachalote','Golfinho',
  'Boto-cor-de-rosa','Foca','Leão-marinho','Morsa','Elefante-marinho','Pinguim',
  'Tubarão Branco','Tubarão Martelo','Tubarão Baleia','Raia (Arraia)','Manta',
  'Peixe-palhaço (Nemo)','Peixe-cirurgião (Dory)','Cavalo-marinho','Peixe-espada',
  'Peixe-voador','Piranha','Enguia','Enguia Elétrica (Puraquê)','Baiacu','Atum',
  'Salmão','Bacalhau','Sardinha','Tubarão (rep)','Tartaruga Marinha',
  'Polvo','Lula','Lula Gigante','Sépia (Choco)','Medusa (Água-viva)',
  'Estrela-do-mar','Ouriço-do-mar','Caranguejo','Siri','Lagosta','Camarão',
  'Amêijoa (Concha)','Ostra (Pérola)','Coral','Esponja-do-mar',
  'Peixe-boi (rep)','Peixe-pedra','Cavalo-marinho (rep)','Arraia (rep)',
  // Aves (Conhecidas)
  'Galinha','Galo','Pinto (Pintinho)','Peru','Pato','Marreco','Ganso','Cisne',
  'Pavão','Faisão','Avestruz','Ema','Pinguim (rep)','Flamingo','Garça',
  'Cegonha','Pelicano','Albatroz','Gaivota','Pomba (Pombo)','Rolinha',
  'Beija-flor (Colibri)','Passarinho','Bem-te-vi','Sabiá','João-de-barro',
  'Canário','Pintassilgo','Benteví (rep)','Tico-tico','Tico-tico no Fubá',
  'Pardal','Andorinha','Coruja','Mocho','Gavião','Águia','Condor','Urubu',
  'Abutre','Falcão','Papagaio','Arara Azul','Arara Vermelha','Tucano',
  'Cacatua','Calopsita','Periquito','Agapornis','Canário Belga',
  'Galo da Serra','Pica-pau','Curió','Canário da Terra','Galinha d\'Angola',
  'Codorna','Perdiz','Emu (rep)','Kiwi (ave)','Cassuar','Ave-do-paraíso',
  // Répteis e Anfíbios
  'Jacaré','Crocodilo','Aligátor','Gavial','Cobra (Serpente)','Cascavel',
  'Coral (Cobra)','Naja','Naja (rep)','Anaconda (Sucuri)','Pitão','Boa',
  'Jiboia','Mamba Negra','Víbora','Lagarto','Teiú','Calango','Camaleão',
  'Lagartixa','Iguana','Dragão de Komodo','Tartaruga de Terra','Jabuti',
  'Cágado','Cágado de barbicha','Sapo','Rã','Perereca','Salamandra',
  'Tritão','Axolote','Dinossauro (Geral)','Tiranossauro Rex','Tricerátops',
  'Diplodoco','Velociraptor','Pterodáctilo','Espinossauro','Anquilossauro',
  'Estegossauro','Braquiossauro (rep)','Iguanodonte','Megalodonte',
  // Insetos e Pequenos Invertebrados
  'Abelha','Zangão','Vespa','Marimbondo','Formiga','Formigueiro',
  'Besouro','Joaninha','Borboleta','Lagarta (Bicho-da-seda)','Mariposa',
  'Mosca','Mosquito (Pernilongo)','Muriçoca (rep)','Vaga-lume (Pirilampo)',
  'Gafanhoto','Esperança (inseto)','Grilo','Louva-a-deus','Barata',
  'Escorpião','Aranha','Tarântula','Viúva Negra (aranha)','Caranguejeira',
  'Centopeia (Lacraia)','Piolho-de-cobra','Escorpião (rep)','Carrapato',
  'Pulga','Piolho','Ácaro','Cupim','Cigarra','Libélula (Lavadeira)',
  'Bicho-pau','Percevejo','Pulga de areia','Mosca varejeira','Zangão (rep)',
  'Minhoca','Caracol (Caramujo)','Lesma','Sanguessuga','Verme',
  // Animais do Folclore e Fantasia (Pop)
  'Dragão (rep)','Unicórnio (rep)','Fênix (rep)','Pégaso','Grifo',
  'Lobisomem (rep)','Vampiro (rep)','Sereia (rep)','Tritão (rep)','Centauro (rep)',
  'Minotauro (rep)','Hidra','Cérbero','Quimera','Esfinge','Basilisco',
  'Kraken','Leviatã','Pé Grande (Yeti)','Monstro do Lago Ness','Chupacabra',
  'Saci (Persona animal - rep)','Mula sem Cabeça (rep)','Boitatá','Curupira (rep)',
  'Iara (rep)','Cuca (Jacaré)','Boizinho (Bumba meu boi)','Fada (rep)','Elfo',
  'Gnomo','Duende','Leprechaun','Troll','Ogro','Gigante',
  // Animais da Cultura Pop (Ficção)
  'Pikachu','Simba','Bambi','Dumbo','Mickey (Rato)','Donald (Pato)',
  'Pateta (Cão)','Pluto','Scooby-Doo','Snoopy','Garfield','Tom (Gato)',
  'Jerry (Rato)','Pica-pau (rep)','Pernalonga (Coelho)','Patolino',
  'Tweety (Piu-piu)','Frajola (Gato)','Babu (Urso)','Zé Colmeia','Catatau',
  'Manda-chuva','Tartarugas Ninja','Donatelo','Rafael','Michelangelo','Leonardo',
  'Kung Fu Panda (Po)','Mestre Shifu','Mestre Tartaruga','Banguela (Fúria da Noite)',
  'Rex (Toy Story)','Slinky (Cão mola)','Babe (O Porquinho Atrapalhado)',
  'Lassie','Beethoven (São Bernardo)','Marley (Labrador)','Flipper (Golfinho)',
  'Willy (Baleia)','Godzilla','King Kong','Jaws (Tubarão)','Cujo',
  'Frankenstein (rep)','Hedwig (Coruja do Harry)','Bicuço (Hipogrifo)',
  'Aragogue (Aranha)','Fawkes (Fênix)','Nagini (Cobra)','Perebas (Rato)',
  'Chewbacca','Yoda','Grogu (Baby Yoda)','Sonic (Ouriço)','Tails','Knuckles',
  'Donkey Kong','Crash Bandicoot','Spyro (Dragão)','Pikachu (rep)','Charmander',
  'Squirtle','Bulbasaur','Mewtwo','Meowth','Jigglypuff','Psyduck',
  'Snorlax','Eevee','Togepi','Lugia','Charizard','Rayquaza',
  // Animais Brasileiros Emblemáticos
  'Arara-azul','Tuiuiú (Símbolo do Pantanal)','Onça-pintada (rep)',
  'Mico-leão-dourado (rep)','Lobo-guará','Tamanduá-bandeira (rep)',
  'Boto-cor-de-rosa (rep)','Peixe-boi-da-amazônia','Jacaré-açu','Sucuri',
  'Jararaca','Urutu-cruzeiro','Coral-verdadeira','Gambá-de-orelha-preta',
  'Sagui-de-tufos-brancos','Cutia','Paca','Tatu-galinha','Tatu-bola (Fuleco)',
  'Ariranha','Piranha-vermelha','Tambaqui','Pirarucu','Tucunaré',
  'Dourado (Peixe)','Surubim (Pintado)','Lambari','Tilápia','Cascudo',
  'Sabiá-laranjeira (Ave nacional)','Uirapuru','Galo-da-serra','Garça-branca',
  'Urubu-rei','Gavião-real (Harpia)','João-de-barro (rep)','Quero-quero (rep)',
  'Ema (rep)','Borboleta-azul','Mariposa-imperador','Vaga-lume','Abelha-europa',
  'Besouro-hércules','Formiga-saúva','Formiga-quem-quem','Carrapato-estrela',
  'Escorpião-amarelo (rep)','Aranha-armadeira','Aranha-marrom',
];
export const ANIMAIS_POP_TOTAL = 835; // ~835 items
