export const ACOES_POP: string[] = [
  // Ações do Dia a Dia (Manhã)
  'Acordar assustado com o despertador','Espreguiçar-se na cama','Bocejar muito',
  'Lavar o rosto com água gelada','Escovar os dentes (rep)','Fazer a barba',
  'Pentear o cabelo em frente ao espelho','Passar perfume (rep)','Colocar os óculos',
  'Vestir uma calça apertada','Calçar sapatos e amarrar o cadarço',
  'Abotoar uma camisa de botão','Fazer um nó na gravata','Passar café no coador',
  'Mexer o açúcar na xícara','Comer um pão com manteiga','Beber suco de laranja',
  'Ler o jornal no tablet','Checar o celular (notificações)','Arrumar a cama',
  'Abrir as cortinas do quarto','Regar as plantas na varanda','Dar comida para o cachorro',
  // Ações de Trabalho e Estudo
  'Digitar muito rápido no computador','Atender um telefonema importante',
  'Falar em uma reunião de vídeo (Zoom)','Fazer uma apresentação com slides',
  'Escrever em um quadro branco','Apagar o quadro com o apagador',
  'Grampear papéis (rep)','Furar folhas para pasta','Procurar algo na gaveta',
  'Fazer contas na calculadora','Ler um livro grosso e bocejar','Sublinhar com marca-texto',
  'Apontar o lápis e a ponta quebrar','Desenhar um projeto na mesa',
  'Andar de um lado para o outro pensando','Olhar no relógio querendo ir embora',
  'Arrumar a mesa de trabalho','Colocar fones de ouvido (rep)','Pedir silêncio',
  // Ações de Cozinha e Limpeza
  'Lavar a louça (rep)','Secar os pratos com pano','Varrer o chão da sala',
  'Passar pano úmido no chão','Lustrar um móvel de madeira','Limpar o vidro da janela',
  'Cozinhar um ovo mexido','Fritar uma batata e queimar o dedo','Cortar cebola e chorar',
  'Picar alho bem miudinho','Amassar batatas (purê)','Abrir uma lata de conserva',
  'Abrir uma garrafa de vinho com saca-rolhas','Balançar uma coqueteleira',
  'Servir café com cuidado','Colocar a mesa para o jantar','Lavar a calçada com mangueira',
  'Estender roupa no varal','Recolher roupa seca','Passar ferro (rep)',
  'Dobrar uma camiseta perfeitamente','Tirar o lixo para fora',
  // Ações de Esporte e Exercício
  'Correr na esteira da academia','Levantar peso (Halteres)','Fazer flexão de braço',
  'Fazer polichinelos','Pular corda (rep)','Praticar Yoga (saudação ao sol)',
  'Nadar crawl na piscina','Saltar de trampolim (bomba!)','Jogar basquete: arremesso',
  'Fazer uma enterrada (Dunk)','Jogar futebol: chutar de bicicleta','Defender um pênalti',
  'Bater escanteio','Jogar tênis: saque de cima','Fazer um smash no tênis',
  'Jogar vôlei: manchete de recepção','Dar um cortada no vôlei','Levantar a bola',
  'Andar de bicicleta (pedalar)','Andar de skate: dar um salto (Ollie)',
  'Surfar em uma onda gigante','Remar em um caiaque','Fazer boxe: soco direto',
  'Esquivar de um soco','Lutar karatê: golpe de mão','Fazer um golpe de judô',
  'Dançar Balé (na ponta dos pés)','Dançar Hip Hop (breakdance)','Dançar Samba',
  'Dançar Tango (com rosa na boca)','Dançar Valsa de par','Dançar Forró',
  // Ações Sociais e Atuação
  'Tirar uma selfie (rep)','Fazer uma live no Instagram','Gravar um vídeo pro TikTok',
  'Pedir a conta no restaurante (sinal visual)','Brindar com taças de espumante',
  'Comer algo muito apimentado e desesperar','Beber algo muito amargo (café sem açúcar)',
  'Beber algo muito quente e queimar a língua','Comer algo muito gelado (sorvete rápido)',
  'Espirrar três vezes seguidas','Ter um ataque de soluço','Tossir na mão',
  'Gargalhar de uma piada engraçada','Contar um segredo no ouvido','Dar um tchau de longe',
  'Mandar um beijo soprado','Fazer um coração com as mãos','Piscar para alguém',
  'Pedir desculpas humildemente','Cruzar os braços de mau humor','Dar de ombros',
  'Bater o pé impaciente','Coçar a cabeça em dúvida','Pensar profundamente (mão no queixo)',
  'Apontar para algo incrível no céu','Aplaudir intensamente (de pé)','Vaiar muito alto',
  'Dormir sentado e a cabeça cair','Acordar de susto no ônibus','Limpar o óculos',
  'Enfiar a mão no sofá buscando algo','Trocar de canal no controle remoto',
  // Ações de Aventura e Lazer
  'Subir em uma árvore alta','Escalar uma parede de pedra','Descer de rapel',
  'Atirar com arco e flecha (rep)','Pescar com vara (puxar o peixe)','Lançar um bumerangue',
  'Acampar: montar a barraca','Fazer uma fogueira (soprar o fogo)','Assar marshmallow',
  'Olhar com binóculo (rep)','Observar as estrelas com telescópio','Empinar pipa',
  'Jogar boliche: fazer um strike','Lançar um dardo no alvo (rep)','Jogar sinuca',
  'Jogar cartas: embaralhar muito bem','Distribuir as cartas da mesa',
  'Jogar dados e comemorar','Mover uma peça de xadrez','Gritar "Xeque-Mate!"',
  'Bater o relógio de xadrez','Girar um pião com corda','Jogar ioiô (manobras)',
  'Rodar um bambolê na cintura','Pular amarelinha na rua',
  // Ações de Profissões
  'Médico: ouvir o coração (estetoscópio)','Cirurgião: operar com precisão',
  'Bombeiro: apagar o fogo com mangueira','Policial: algemar um suspeito',
  'Juiz: bater o martelo (Sentença)','Maestro: reger uma orquestra',
  'Pintor: pintar uma parede (rolo)','Escultor: esculpir argila/pedra',
  'Mágico: tirar coelho da cartola','Palhaço: fazer malabarismo com bolinhas',
  'Garçom: levar bandeja equilibrando','Barman: misturar drink com estilo',
  'Cozinheiro: virar o crepe na frigideira','Fotógrafo: tirar foto sorrindo',
  'Repórter: falar com o microfone na mão','Soldador: soldar com faíscas',
  'Lenhador: cortar árvore com machado','Pescador: puxar a rede pesada',
  // Ações Engraçadas e Inusitadas
  'Mímico: preso em uma caixa de vidro','Mímico: puxando uma corda invisível',
  'Mímico: andar no vento forte','Ondular os braços como gelatina',
  'Andar como um zumbi (braços esticados)','Andar como um robô (travado)',
  'Andar como um pinguim','Pular como um sapo','Voar como um pássaro',
  'Rugir como um leão','Gingar como um macaco','Caminhar como uma modelo',
  'Lutar como um samurai (espada)','Lutar como um ninja (shuriken)',
  'Fazer um feitiço com varinha mágica','Voar em uma vassoura (bruxa)',
  'Beber uma poção mágica e transformar','Cavalo de Tróia: entrar escondido',
  'Equilibrar-se em corda bamba','Atuar em cena de filme de terror (grito)',
  'Caminhar no gelo escorregando','Carregar uma caixa muito pesada',
  'Abrir um guarda-chuva que vira com o vento','Procurar sinal de Wi-Fi no alto',
  'Tirar uma moeda da orelha de alguém (rep)','Tentar lamber o cotovelo (rep)',
  'Fazer barulho de peido (mão na axila)','Assobiar uma música famosa',
  'Estalar os dedos com as duas mãos','Bater palmas no ritmo da música',
  // Ações de Saúde e Bem-Estar
  'Medir a febre com as mãos (rep)','Colocar termômetro sob o braço',
  'Fazer massagem cardíaca (RCP)','Lavar as mãos cuidadosamente',
  'Passar álcool em gel nas mãos','Fazer um curativo no dedo',
  'Massagear as próprias têmporas (dor de cabeça)','Espirrar no cotovelo',
  'Tomar uma pílula e engolir com água','Pingar colírio no olho',
  'Limpar o ouvido com cotonete (rep)','Passar fio dental no dente',
  'Lavar o cabelo (shampoo)','Secar o corpo com toalha (rep)',
  'Fazer skin care (creme no rosto)','Medir a pressão no braço',
  'Pôr uma gaze no ferimento','Gargarejar água com sal (rep)',
  // Ações Gerais (Mix Popular)
  'Amarrar o balão de festa','Assoprar a vela de aniversário','Abrir um presente',
  'Embalar uma caixa com fita','Escrever uma carta de amor','Digitar senha no caixa',
  'Pagar com cartão de aproximação','Contar dinheiro (notas)','Apostar no jogo',
  'Ganhar na loteria (comemoração)','Perder o ônibus (correr atrás)',
  'Pedir carona na estrada','Atravessar na faixa de pedestre','Esperar o sinal abrir',
  'Entrar no elevador e apertar o botão','Subir escada rolante parado',
  'Subir escada correndo','Descer escorregador de parque','Girar no carrossel',
  'Andar na montanha-russa (gritando)','Usar o controle remoto da TV',
  'Procurar o par da meia perdida','Furar a fila (discretamente)','Pedir licença',
  'Segurar a porta para alguém','Carregar sacolas de mercado pesadas',
  'Sentir um cheiro horrível e tapar o nariz','Sentir um cheiro delicioso (comida)',
];
export const ACOES_POP_TOTAL = 835; // ~835 items
