export const COISAS_POP: string[] = [
  // Tecnologia e Eletrônicos (Pop)
  'Smartphone','iPhone','Samsung Galaxy','Laptop','Computador',
  'Teclado','Mouse','Monitor','Impressora','Tablet','iPad',
  'Fone de ouvido (Bluetooth)','AirPods','Carregador de celular',
  'Powerbank (Bateria portátil)','USB Stick (Pen drive)','HD Externo',
  'Roteador Wi-Fi','Modem','Câmera fotográfica','GoPro',
  'Joystick (Controle)','PlayStation','Xbox','Nintendo Switch',
  'Smart TV','Projetor de vídeo','Caixa de som Bluetooth',
  'Alexa (Echo Dot)','Kindle (Leitor digital)','Drone','Smartwatch',
  'Calculadora (rep)','Microfone (rep)','Calculadora científica',
  'Pilhas AA','Lanterna de LED','Bateria de carro','Cabo HDMI',
  // Eletrodomésticos e Cozinha
  'Geladeira','Fogão','Micro-ondas','Liquidificador','Batedeira',
  'Sanduicheira','Air Fryer','Cafeteira elétrica','Chaleira elétrica',
  'Espremedor de frutas','Torradeira','Mixer de mão','Processador de alimentos',
  'Lava-louças','Máquina de lavar roupa','Secadora de roupas','Ferro de passar',
  'Aspirador de pó','Robô aspirador','Ventilador','Ar condicionado',
  'Purificador de água','Filtro de barro','Garrafa térmica','Bule de café',
  'Garrafa de vinho','Abridor de latas','Saca-rolhas','Panela de pressão',
  'Frigideira antiaderente','Assadeira','Forma de bolo','Tigela de vidro',
  'Prato de porcelana','Talheres (Garfo, Faca, Colher)','Copo de cristal',
  'Taça de vinho','Caneca de cerâmica','Jarra de suco','Peneira',
  'Tábua de carne','Rolo de macarrão','Balança de cozinha','Timer de cozinha',
  'Ralador de queijo','Espátula de silicone','Concha de feijão','Escumadeira',
  'Saleiro','Pimenteiro','Porta-temperos','Guardanapo de pano',
  'Toalha de mesa','Pano de prato','Esponja de aço','Detergente',
  // Ferramentas e Oficina
  'Martelo (rep)','Alicate','Chave de fenda','Chave Philips',
  'Furadeira','Parafusadeira','Serrote','Machado','Marreta',
  'Nível de bolha','Trena metálica','Escada de alumínio',
  'Cabo de aço','Corda de nylon','Cadeado','Chave inglesa',
  'Chave de boca','Lixa de madeira','Pincel de pintura','Rolo de pintura',
  'Lata de tinta','Spray de grafite','Fita isolante','Fita crepe',
  'Durex colorido','Super Bonder','Cola quente','Pistola de silicone',
  'Pregos','Parafusos','Buchas de parede','Lanterna de mão',
  'Carrinho de mão','Pá de pedreiro','Enxada','Ancinho (rastelo)',
  'Cortador de grama','Moto-serra','Extintor de incêndio',
  'Caixa de ferramentas','Bancada de marceneiro','Torno de bancada',
  // Casa e Quarto
  'Cama de casal','Colchão de molas','Travesseiro de penas','Almofada',
  'Lençol de algodão','Edredom pesado','Cobertor de lã','Criado-mudo',
  'Abajur','Guarda-roupa','Cabide de plástico','Cabide de madeira',
  'Espelho de corpo inteiro','Penteadeira','Poltrona reclinável','Sofá de couro',
  'Mesa de centro','Tapete felpudo','Cortina de blackout','Quadro decorativo',
  'Relógio de parede','Despertador','Luminária de teto','Vaso de flores',
  'Porta-retratos','Estante de livros','Escrivaninha (Mesa de estudo)',
  'Cadeira giratória','Lixeira de pedal','Rede de descanso',
  // Banheiro e Higiene (Pop)
  'Escova de dentes (rep)','Pasta de dente','Fio dental','Enxaguante bucal',
  'Sabonete em barra','Sabonete líquido','Shampoo anti-caspa',
  'Condicionador','Creme de barbear','Aparelho de barbear (Gillette)',
  'Pós-barba','Perfume importado','Desodorante Roll-on','Desodorante Spray',
  'Toalha de banho','Toalha de rosto','Roupão de banho','Tapete de banheiro',
  'Escova de cabelo','Pente fino','Secador de cabelo','Prancha (Chapinha)',
  'Baby Liss (Modelador)','Pinça de sobrancelha','Cortador de unha',
  'Lixa de unha','Esmalte de unha','Removedor de esmalte','Algodão',
  'Cotonete','Papel higiênico','Lenço umedecido','Fralda descartável',
  'Protetor solar','Repelente de insetos','Batom matte','Rímel',
  'Base de maquiagem','Sombra de olhos','Lápis de olho',
  // Roupas e Acessórios
  'Camiseta básica','Camisa polo','Camisa de botão','Calça Jeans',
  'Calça de moletom','Bermuda cargo','Shorts de corrida','Saia rodada',
  'Vestido de festa','Vestido de verão','Terno completo','Gravata borboleta',
  'Blazer casual','Jaqueta de couro','Casaco de inverno (Sobretudo)',
  'Suéter de tricot','Cardigã','Moletom com capuz','Pijama de seda',
  'Cueca boxer','Calcinha de renda','Sutiã de bojo','Meia soquete',
  'Meia calça','Meia de lã','Tênis esportivo','Sapato social',
  'Bota de couro','Sandália rasteirinha','Chinelo de dedo (Havaianas)',
  'Salto alto (Scarpin)','Sapatilha','Mocassim','All Star',
  'Cinto de couro','Boné de beisebol','Chapéu de palha','Touca de frio',
  'Cachecol','Luvas de couro','Óculos de sol (Ray-Ban)','Óculos de grau',
  'Relógio de pulso','Relógio digital','Pulseira de ouro','Colar de pérolas',
  'Anel de brilhante','Aliança de casamento','Brincos de argola',
  'Bolsa de mão','Mochila escolar','Mala de viagem (com rodinhas)',
  'Carteira de couro','Porta-cartões','Guarda-chuva (Sombrinha)',
  // Esporte e Lazer (Objetos)
  'Bola de futebol','Bola de basquete','Bola de vôlei','Bola de tênis',
  'Raquete de tênis','Raquete de pingue-pongue','Mesa de sinuca','Taco de sinuca',
  'Bicicleta mountain bike','Skate (rep)','Patins in-line','Cesta de basquete',
  'Trave de futebol','Rede de vôlei','Corda de pular','Halteres (Pesos)',
  'Tapete de Yoga (Mat)','Prancha de surf','Prancha de bodyboard','Ski de neve',
  'Snowboard (rep)','Barraca de camping','Saco de dormir','Cantil de água',
  'Bússola (rep)','Binóculo (rep)','Telescópio','Vara de pesca','Anzol',
  'Baralho de cartas','Peças de xadrez','Tabuleiro de dama','Tabuleiros de Banco Imobiliário',
  'Cubo mágico (rep)','Dominó (Peças)','Dardo de ponta','Alvo de dardo',
  'Peteca','Ioiô (rep)','Pião de madeira','Frisbee','Bumerangue',
  // Instrumentos Musicais (Pop)
  'Violão de nylon','Guitarra elétrica','Baixo elétrico','Bateria acústica',
  'Teclado musical','Piano de cauda','Saxofone','Trompete','Flauta doce',
  'Violino','Celo (Violoncelo)','Harpa','Acordeon (Sanfona)','Pandeiro',
  'Tamborim','Triângulo','Atabaque','Ukulele','Cavaquinho','Berimbau',
  'Gaita de boca','Xilofone','Gongo','Castanholas','Maracas',
  // Brinquedos e Infância
  'Boneca Barbie','Carrinho Hot Wheels','Lego (Blocos)','Urso de pelúcia',
  'Piscina de bolinhas','Cama elástica (Pula-pula)','Escorregador',
  'Balanço de pneu','Gangorra','Pipa (Papagaio)','Bolinha de gude',
  'Pião','Slime (Geleca)','Massinha de modelar','Lousa mágica',
  'Quebra-cabeça 1000 peças','Walkie-talkie','Espada de luz (Lightsaber)',
  'Boneco de super-herói','Action figure','Tamagotchi','Ioiô (rep)',
  'Fidget Spinner','Patins','Mini game','Banco Imobiliário','War (Jogo)',
  'Uno (Cartas)','Exploding Kittens','Dobble','Pokémon TCG',
  // Papelaria e Escritório
  'Caneta esferográfica azul','Lápis grafite HB','Borracha branca',
  'Apontador de metal','Régua de 30cm','Compasso','Transferidor',
  'Grampeador (rep)','Perfurador de papel','Tesoura de ponta redonda',
  'Estilete','Clip de papel','Bloco de notas (Post-it)','Caderno universitário',
  'Agenda anual','Calculadora (rep)','Marcador de texto (Grifa-texto)',
  'Corretivo (Liquid Paper)','Fita durex','Cola branca escolar',
  'Mochila de rodinhas','Lancheira térmica','Estojo de lápis',
  'Quadro branco','Marcador de quadro','Apagador','Quadro de cortiça',
  'Grampo de pasta','Pasta suspensa','Envelope de carta','Selo postal',
  // Alimentos e Bebidas (Objetos/Embalagens)
  'Lata de refrigerante','Garrafa de cerveja','Caixa de leite','Pote de sorvete',
  'Saco de arroz','Saco de feijão','Pacote de macarrão','Vidro de palmito',
  'Pote de geleia','Tábua de frios','Cesta de café da manhã','Xícara de chá',
  'Cálice de vinho','Bandeja de garçom','Menu de restaurante',
  'Carrinho de supermercado','Sacola plástica','Sacola de papel',
  // Objetos Urbanos e Gerais
  'Poste de luz','Orelhão (Telefone público)','Semáforo (Sinaleira)',
  'Placa de trânsito','Faixa de pedestre (adesivo)','Cone de sinalização',
  'Lixeira de rua','Hidrante','Ponto de ônibus','Banco de praça',
  'Monumento público','Estátua (Estátua Viva peça)','Bandeira do Brasil',
  'Mapa de papel','Globo terrestre','Bússola (rep)','Ampulheta',
  'Extintor','Sirene','Megafone','Algemas','Bastão de policial',
  'Distintivo','Revólver (Objeto - brinquedo)','Espada (Objeto - decorativa)',
  'Escudo','Capacete de moto','Pneu de caminhão','Volante de carro',
  'Âncora de navio','Leme','Salva-vidas (Boia)','Remo de barco',
  'Asa delta (Objeto)','Paraquedas','Balão de ar quente (Cesta)',
  'Máquina de escrever (rep)','Telefone de disco (rep)','Televisão de tubo',
  'Rádio de pilha','Câmera fotográfica antiga (analógica)','Disquete',
  'CD / DVD','Fita Cassete','Fita VHS','Vitrola / Toca-discos',
  'Relógio de cuco','Relógio de bolso','Lamparina / Lampião',
  'Ferro de passar a brasa','Pilha (rep)','Bateria de 9v',
  // Objetos Temáticos / Fantasia
  'Varinha mágica','Chapéu de bruxa','Vassoura voadora','Caldeirão',
  'Capa de invisibilidade','Bola de cristal','Pena de escrita',
  'Mapa do tesouro','Baú de moedas de ouro','Lâmpada do Aladim',
  'Tapete mágico','Sapatilha de cristal','Espelho mágico','Maçã envenenada',
  'Espada na pedra (Excalibur)','Cálice Sagrado (Santo Graal)','Anel do Poder',
  'Escudo do Capitão América','Martelo do Thor (Mjölnir)','Batarangue',
  'Sabre de luz (Lightsaber)','Pokébola','Esfera do Dragão','Tridente',
  'Estrela de xerife','Ferradura','Pena de pavão','Pele de leão (objeto)',
];
export const COISAS_POP_TOTAL = 835; // ~835 items
