export const FILMES_POP: string[] = [
  // Franquias de Bilheteria (Globale)
  'Star Wars: Uma Nova Esperança','Darth Vader (rep)','O Império Contra-Ataca',
  'O Retorno de Jedi','A Ameaça Fantasma','O Ataque dos Clones','A Vingança dos Sith',
  'O Despertar da Força','Os Últimos Jedi','A Ascensão Skywalker','Rogue One',
  'Han Solo (O Filme)','Harry Potter e a Pedra Filosofal','A Câmara Secreta',
  'O Prisioneiro de Azkaban','O Cálice de Fogo','A Ordem da Fênix','O Enigma do Príncipe',
  'As Relíquias da Morte','Animais Fantásticos','O Senhor dos Anéis: A Sociedade do Anel',
  'As Duas Torres','O Retorno do Rei','O Hobbit: Uma Jornada Inesperada',
  'A Desolação de Smaug','A Batalha dos Cinco Exércitos','Vingadores (Avengers)',
  'Vingadores: Era de Ultron','Vingadores: Guerra Infinita','Vingadores: Ultimato',
  'Homem de Ferro','Capitão América: O Primeiro Vingador','O Soldado Invernal',
  'Guerra Civil','Thor','Thor: Ragnarok','Hulk','Pantera Negra','Viúva Negra',
  'Guardiões da Galáxia','Doutor Estranho','Homem-Aranha: De Volta ao Lar',
  'Longe de Casa','Sem Volta para Casa','Eternos','Shang-Chi','The Batman',
  'O Cavaleiro das Trevas','Batman Begins','O Cavaleiro das Trevas Ressurge',
  'Superman: O Homem de Aço','Batman vs Superman','Mulher-Maravilha','Liga da Justiça',
  'Aquaman','Shazam!','Esquadrão Suicida','O Esquadrão Suicida (2021)','Coringa (Joker)',
  'Transformers','Bumblebee','Velozes e Furiosos','Missão Impossível','John Wick',
  '007: Cassino Royale','Skyfall','Piratas do Caribe: A Maldição do Pérola Negra',
  'Jurassic Park (rep)','Jurassic World','Avatar (rep)','Titanic','E.T. O Extraterrestre',
  'De Volta para o Futuro','Indiana Jones e os Caçadores da Arca Perdida','Tubarão (Jaws)',
  'Rocky Balboa','Rambo: Programado para Matar','Creed: Nascido para Lutar',
  'Top Gun: Maverick','Mad Max: Estrada da Fúria','Gladiador','Braveheart (Coração Valente)',
  'The Matrix','Exterminador do Futuro 2','Duro de Matar','Alien: O Oitavo Passageiro',
  'Predador','Robocop','O Poderoso Chefão','Pulp Fiction','Forrest Gump',
  'O Rei Leão (rep)','A Bela e a Fera','Aladdin','A Pequena Sereia','Mulan',
  'Toy Story (rep)','Toy Story 2','Toy Story 3','Toy Story 4','Procurando Nemo',
  'Os Incríveis (rep)','Monstros S.A.','Up: Altas Aventuras','Carros (McQueen)',
  'Frozen: Uma Aventura Congelante','Frozen 2','Moana','Enrolados','Viva: A Vida é uma Festa',
  'Encanto','Luca','Red: Crescer é uma Fera','Shrek (rep)','Shrek 2','Shrek Terceiro',
  'Shrek para Sempre','Kung Fu Panda','Madagascar','Era do Gelo',
  'Como Treinar o Seu Dragão','Minions','Meu Malvado Favorito','Pets: A Vida Secreta dos Bichos',
  'Sing: Quem Canta Seus Males Espanta','Homem-Aranha no Aranhaverso','Spider-Man Across the Spider-Verse',
  // Cinema Brasileiro (Pop)
  'Cidade de Deus','Tropa de Elite','Tropa de Elite 2','Central do Brasil',
  'O Auto da Compadecida','Lisbela e o Prisioneiro','Se Eu Fosse Você','Se Eu Fosse Você 2',
  'Minha Mãe é uma Peça (rep)','Minha Mãe é uma Peça 2','Minha Mãe é uma Peça 3',
  'Bacurau','Hoje Eu Quero Voltar Sozinho','Que Horas Ela Volta?','Carandiru',
  'O Som ao Redor','Estômago','Mariguella','Pixote','Vidas Secas (filme)',
  'O Pagador de Promessas','Terra em Transe','Deus e o Diabo na Terra do Sol',
  'A Grande Família o Filme','Cine Holliúdy','O Palhaço','Xuxa Abracadabra',
  'Lua de Cristal','Super Xuxa','Acquária','Mussum, o Filmis','Nosso Lar',
  // Séries Populares (Mundiais e Br)
  'Game of Thrones','Stranger Things','La Casa de Papel','Grey\'s Anatomy',
  'The Walking Dead','Breaking Bad','Better Call Saul','Os Simpsons','Friends',
  'The Big Bang Theory','How I Met Your Mother','Modern Family','The Office (EUA)',
  'The Office (UK)','Brooklyn Nine-Nine','Sex Education','Elite','The Crown',
  'Succession','Euphoria','The Last of Us (série)','The Mandalorian','The Boys',
  'Bridgerton','Lupin','Cobra Kai','Vandinha (Wednesday)','Lucifer','The Witcher',
  'The Umbrella Academy','Black Mirror','Dark','Chernobyl','Mindhunter','Sherlock',
  'Peaky Blinders','Narcos','Sintonia','Carcereiros','Sob Pressão','Bom Dia Verônica',
  'O Clone (rep)','Avenida Brasil (rep)','Pantanal (Remake)','Vale Tudo (Novela)',
  'Sítio do Picapau Amarelo','Castelo Rá-Tim-Bum','A Praça é Nossa','Sai de Baixo',
  'Novela das Nove','Tapas e Beijos','Os Normais','Sob Nova Direção','Chaves (rep)',
  'Chapolin Colorado (rep)','Squid Game (Round 6)','All of Us Are Dead','Kingdom',
  'Dragon Ball Z (rep)','Naruto (rep)','One Piece','Pokémon (rep)','Cavaleiros do Zodíaco',
  'Yu-Gi-Oh!','Digimon','Death Note','Sailor Moon','Evangelion','Attack on Titan',
  'Demon Slayer','Jujutsu Kaisen','My Hero Academia','Fullmetal Alchemist',
  // Terror e Suspense (Pop)
  'O Exorcista','O Iluminado','Psicose','O Silêncio dos Inocentes','Halloween (Michael Myers)',
  'Sexta-Feira 13 (Jason)','A Hora do Pesadelo (Freddy Krueger)','Brinquedo Assassino (Chucky)',
  'It: A Coisa','Invocação do Mal','Annabelle','O Chamado (Samara)','O Grito',
  'Pânico (Ghostface)','Jogos Mortais (Jigsaw)','Atividade Paranormal','Corra! (Get Out)',
  'Nós (Us)','Hereditário','Midsommar','Um Lugar Silencioso','Bird Box',
  // Clássicos Absolutos
  'Casablanca','Cidadão Kane','Psicose (rep)','2001: Uma Odisséia no Espaço',
  'Cantando na Chuva','O Mágico de Oz','E o Vento Levou','Bonequinha de Luxo',
  'Ben-Hur','A Vida é Bela','A Lista de Schindler','O Pianista','Clube da Luta',
  'Beleza Americana','O Sexto Sentido','Os Suspeitos','Se7en: Os Sete Crimes Capitais',
  'Kill Air','Bastardos Inglórios','Django Livre','Pulp Fiction (rep)','Cães de Aluguel',
  'O Show de Truman','Sociedade dos Poetas Mortos','Gênio Indomável','Brilho Eterno de uma Mente sem Lembranças',
  // Super Cine e Afins
  'Lagoa Azul','Esqueceram de Mim','Duro de Matar (rep)','Ghost: Do Outro Lado da Vida',
  'Uma Linda Mulher','Sexta-Feira Muito Louca','Meninas Malvadas','As Branquelas',
  'O Diabo Veste Prada','Legalmente Loira','De Repente 30','Como Perder um Homem em 10 Dias',
  'Sr. e Sra. Smith','Doze Homens e Outro Segredo','O Espetacular Homem-Aranha',
  'V de Vingança','Blade Runner','Donnie Darko','Labirinto do Fauno','O Hobbit (rep)',
  'Percy Jackson','Crepúsculo (Twilight)','Lua Nova','Eclipse','Amanhecer',
  'Jogos Vorazes (Hunger Games)','Divergente','Maze Runner','Ted','Se Beber Não Case',
  'Superbad','American Pie','Projeto X','Click','O Todo Poderoso',
  'Show de Vizinha','Amizade Colorida','Vizinhos','Quase Irmãos','Mestre dos Mares',
  // Séries Antigas (Nostalgia)
  'MacGyver (Profissão Perigo)','Knight Rider (A Super Máquina)','A-Team (Esquadrão Classe A)',
  'Smallville (rep)','Supernatural (rep)','Lost (rep)','Prision Break','Heroes',
  'Arquivo X (The X-Files)','Buffy','Xena: A Princesa Guerreira','Hercules',
  'Um Maluco no Pedaço (Fresh Prince)','Todo Mundo Odeia o Chris','Eu, a Patroa e as Crianças',
  'Kenan e Kel','Três é Demais (Full House)','Alf: O Eteimoso','Punky: A Levada da Breca',
  'Anos Incríveis','A Feiticeira','Jeannie é um Gênio','Batman (Adam West)',
  // Reality Shows
  'Big Brother Brasil (BBB)','A Fazenda','MasterChef','No Limite','The Voice Brasil',
  'The Masked Singer','De Férias com o Ex','Casamento às Cegas','Keeping Up with the Kardashians',
  'RuPaul\'s Drag Race','O Aprendiz','Shark Tank','Largados e Pelados','Cake Boss',
  // Extras Cultura Pop
  'Hogwarts (rep)','Gondor','Marvel Cinematic Universe','DC Extended Universe',
  'Oscar (Cerimônia)','Grammy (Cerimônia)','Copa do Mundo (FIFA)','Olimpíadas',
  'Super Bowl','Carnaval do Rio','Rock in Rio','Lollapalooza','Coachella',
];
export const FILMES_POP_TOTAL = 835; // ~835 items
