export const LUGARES_POP: string[] = [
  // Marcos Turísticos Globais
  'Torre Eiffel','Muralha da China','Estátua da Liberdade','Cristo Redentor',
  'Pirâmides de Gizé','Coliseu de Roma','Taj Mahal','Machu Picchu',
  'Big Ben','Grand Canyon','Cataratas do Iguaçu','Cataratas do Niágara',
  'Monte Everest','Monte Fuji','Deserto do Saara','Floresta Amazônica',
  'Recife de Corais','Antártida','Polo Norte','Ilha de Páscoa',
  'Stonehenge','Acrópole de Atenas','Pantheon','Torre de Pisa',
  'Canais de Veneza','Mar Morto','Rio Nilo','Rio Amazonas','Rio Sena',
  'Rio Tâmisa','Rio Danúbio','Rio Mississipi','Grand Canyon (rep)',
  'Monte Rushmore','Hollywood Sign','Golden Gate Bridge','Empire State Building',
  'Times Square','Central Park','Disneylândia','Disney World','Universal Studios',
  'Louvre','Museu Britânico','Museu do Prado','Vaticano','Basílica de São Pedro',
  'Capela Sistina','Catedral de Notre Dame','Sagrada Família (Barcelona)',
  'Palácio de Versalhes','Castelo de Neuschwanstein','Alhambra','Mesquita Azul',
  'Petra (Jordânia)','Angkor Wat','Cidade Proibida (Pequim)','Burj Khalifa',
  'Palácio de Buckingham','Casa Branca','Kremlin','Praça Vermelha',
  'Ópera de Sydney','Uluru (Ayers Rock)','Table Mountain (Cidade do Cabo)',
  'Lago Ness','Everglades','Yellowstone','Iosemite','Galápagos',
  'Monte Saint-Michel','Salinas de Uyuni','Lençóis Maranhenses','Fernando de Noronha',
  'Pão de Açúcar','Corcovado','Copacabana','Ipanema','Pelourinho',
  'Teatro Amazonas','Museu do Ipiranga','MASP','Avenida Paulista',
  'Congresso Nacional (Brasília)','Catedral de Brasília','Ponte JK',
  // Capitais e Cidades Globais (Mais Conhecidas)
  'Paris','Londres','Nova York','Roma','Tóquio','Pequim','Moscou',
  'Berlim','Madri','Lisboa','Washington D.C.','Ottawa','Cidade do México',
  'Buenos Aires','Santiago','Lima','Bogotá','Quito','Montevidéu',
  'Asunção','La Paz','Caracas','Cidade do Panamá','Havana','Brasília',
  'Rio de Janeiro','São Paulo','Belo Horizonte','Salvador','Fortaleza',
  'Recife','Porto Alegre','Curitiba','Manaus','Belém','Goiânia',
  'Vitória','Florianópolis','João Pessoa','Natal','Maceió','Aracaju',
  'Teresina','São Luís','Cuiabá','Campo Grande','Porto Velho','Rio Branco',
  'Boa Vista','Macapá','Palmas','Cairo','Cidade do Cabo','Johanesburgo',
  'Nairóbi','Casablanca','Marraquexe','Atenas','Viena','Bruxelas',
  'Amsterdã','Copenhague','Estocolmo','Oslo','Helsinque','Varsóvia',
  'Praga','Budapeste','Istambul','Ancara','Jerusalém','Tel Aviv',
  'Dubai','Abu Dhabi','Riade','Doha','Teerã','Bagdá','Cabul',
  'Islamabad','Nova Delhi','Mumbai','Calcutá','Bangalore','Pequim (rep)',
  'Xangai','Cantão','Hong Kong','Taipé','Seul','Bangcoc','Jacarta',
  'Cingapura','Manila','Hanoi','Ho Chi Minh','Sydney','Melbourne',
  'Auckland','Wellington','Honolulu','Las Vegas','Los Angeles',
  'San Francisco','Chicago','Miami','Orlando','Houston','Dallas',
  'Boston','Filadélfia','Toronto','Vancouver','Montreal','Cidade do Vaticano',
  'Mônaco','San Marino','Andorra','Luxemburgo','Liechtenstein','Malta',
  'Reykjavik','Dublin','Glasgow','Edimburgo','Cardiff','Belfast',
  'Lyon','Marselha','Niterói','Veneza','Florença','Milão','Nápoles',
  'Barcelona','Sevilha','Valencia','Granada','Ibiza','Porto','Faro','Coimbra',
  'Funchal','Ponta Delgada','Amalfi','Santorini','Mykonos','Creta',
  'Bali','Phuket','Maldivas','Bora Bora','Seychelles','Maurício',
  'Bahamas','Cancún','Punta Cana','Cartagena (Colômbia)','Gramado',
  'Canela','Blumenau','Joinville','Ushuaia','Bariloche','Cusco',
  'Potosí','Sucre','Galápagos (Ilhas)','Deserto de Atacama',
  'Patagônia','Alasca','Groenlândia','Sibéria','Tibete','Himalaia',
  'Alpes Suíços','Pirineus','Andes','Montanhas Rochosas','Apalaches',
  // Brasil (Cidades Populares Volume 2)
  'Ouro Preto','Diamantina','Mariana','Tiradentes','Congonhas',
  'Olinda','Porto Seguro','Trancoso','Arraial d\'Ajuda','Arraial do Cabo',
  'Cabo Frio','Búzios','Angra dos Reis','Paraty','Ilha Grande',
  'Ilhabela','São Sebastião','Ubatuba','Guarujá','Santos',
  'Campinas','Ribeirão Preto','Sorocaba','São José dos Campos','Jundiaí',
  'Piracicaba','Bauru','São José do Rio Preto','Londrina','Maringá',
  'Cascavel','Foz do Iguaçu','Ponta Grossa','Joinville (rep)','Caxias do Sul',
  'Pelotas','Santa Maria','Passo Fundo','Bento Gonçalves','Garibaldi',
  'Torres','Tramandaí','Capão da Canoa','Praia do Forte','Morro de São Paulo',
  'Itacaré','Arraial do Cabo (rep)','Saquarema','Teresópolis','Petrópolis',
  'Nova Friburgo','Juiz de Fora','Montes Claros','Uberlândia','Uberaba',
  'Ipatinga','Governador Valadares','Feira de Santana','Vitória da Conquista',
  'Campina Grande','Caruaru','Petrolina','Juazeiro do Norte','Sobral',
  'Mossoró','Parnaíba','Imperatriz','Marabá','Santarém','Ji-Paraná',
  'Dourados','Três Lagoas','Rondonópolis','Sinop','Anápolis','Aparecida de Goiânia',
  // Estados Brasileiros (Todos)
  'Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Espírito Santo',
  'Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais',
  'Pará','Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro (Estado)',
  'Rio Grande do Norte','Rio Grande do Sul','Rondônia','Roraima',
  'Santa Catarina','São Paulo (Estado)','Sergipe','Tocantins','Distrito Federal',
  // Países do Mundo (Populares)
  'Brasil','Portugal','Estados Unidos','Angola','Moçambique','Cabo Verde',
  'Guiné-Bissau','São Tomé e Príncipe','Timor-Leste','Espanha','França',
  'Itália','Alemanha','Reino Unido','Rússia','China','Japão','Índia',
  'Canadá','México','Argentina','Chile','Colômbia','Peru','Uruguai',
  'Paraguai','Bolívia','Equador','Venezuela','África do Sul','Egito',
  'Nigéria','Quênia','Marrocos','Austrália','Nova Zelândia','Turquia',
  'Grécia','Suíça','Áustria','Holanda','Bélgica','Suécia','Noruega',
  'Dinamarca','Irlanda','Polônia','Ucrânia','Israel','Arábia Saudita',
  'Catar','Emirados Árabes Unidos','Coreia do Sul','Coreia do Norte',
  'Indonésia','Tailândia','Filipinas','Vietnã','Irã','Iraque','Síria',
  'Cuba','Jamaica','Haiti','Panamá','Costa Rica','Islândia',
  // Mar, Espaço e Natureza Pop
  'Oceano Atlântico','Oceano Pacífico','Oceano Índico','Oceano Ártico',
  'Mar Mediterrâneo','Mar do Caribe','Mar Morto (rep)','Mar Vermelho',
  'Mar Negro','Mar Cáspio','Baía de Guanabara','Baía de Todos os Santos',
  'Estreito de Gibraltar','Canal da Mancha','Canal do Panamá','Canal de Suez',
  'Polo Sul','Lua','Marte','Vênus','Júpiter','Saturno (Anéis)',
  'Urano','Netuno','Mercúrio','Plutão','Sol','Estrela Cadente',
  'Via Láctea','Buraco Negro','Cometa Halley','Andrômeda','Constelação de Órion',
  'Cruzeiro do Sul','Trópico de Câncer','Trópico de Capricórnio','Linha do Equador',
  'Hemisfério Norte','Hemisfério Sul','Antártida (rep)','Groenlândia (rep)',
  'Everest (rep)','K2','Monte Kilimanjaro','Monte Elbrus','Mont Blanc',
  'Cordilheira dos Andes (rep)','Montanhas Rochosas (rep)','Deserto de Gobi',
  'Vale da Morte (EUA)','Delta do Nilo','Foz do Iguaçu (rep)',
  // Bairros Famosos Brasil
  'Copacabana','Ipanema','Leblon','Barra da Tijuca','Botafogo','Flamingo',
  'Lapa','Santa Teresa','Madureira','Bangu','Tijuca','Méier','Jacarepaguá',
  'Moema','Itaim Bibi','Vila Madalena','Pinheiros','Morumbi','Jardins',
  'Liberdade','Bexiga','Braás','Mooca','Tatuapé','Anhembi','Interlagos',
  'Pampulha','Savassi','Lourdes (BH)','Cidade Alta (Salvador)','Pelourinho (rep)',
  'Boa Viagem (Recife)','Aldeota (Fortaleza)','Batunique (rep)','Trindade (rep)',
  // Lugares Fictícios Populares
  'Hogwarts','Nárnia','Terra Média','Gotham City','Metrópolis','Neverland (Terra do Nunca)',
  'País das Maravilhas','Atlântida','El Dorado','Olimpo','Asgard','Valhalla',
  'Pandora (Avatar)','Estrela da Morte','Tatooine','Wakanda','Springfield',
  'Sítio do Picapau Amarelo','Vila do Chaves','Fenda do Biquíni','Radiator Springs',
  'Gotham (rep)','Arkham Asylum','Castelo de Grayskull','Jurassic Park',
  'A Toca (Harry Potter)','Beco Diagonal','Hogsmeade','Mordor','Condado (Hobbit)',
  'Ilha da Caveira','Ilha Nublar','País de Oz','Emerald City (Cidade das Esmeraldas)',
  'Krypton','Smallville (rep)','Westeros','Winterfell','Porto Real (King\'s Landing)',
  'A Muralha (Game of Thrones)','Mundo Invertido (Stranger Things)','Hill Valley (BTTF)',
  'Twin Peaks','South Park','Bikini Bottom (rep)','Halloween Town','Christmas Town',
];
export const LUGARES_POP_TOTAL = 835; // ~835 items
