export const PESSOAS_POP: string[] = [
  // Ícones Globais e Históricos (Conhecimento Geral)
  'Albert Einstein','Isaac Newton','Charles Darwin','Marie Curie','Leonardo da Vinci',
  'Michelangelo','Galileu Galilei','Stephen Hawking','Thomas Edison','Nikola Tesla',
  'Alexander Graham Bell','Santos Dumont','Irmãos Wright','Ada Lovelace','Alan Turing',
  'Bill Gates','Steve Jobs','Mark Zuckerberg','Elon Musk','Jeff Bezos',
  'Rei Arthur','Robin Hood','Joana d\'Arc','Napoleão Bonaparte','Júlio César',
  'Cleópatra','Alexandre o Grande','Gengis Khan','Tutancâmon','Nefertiti',
  'Abraham Lincoln','George Washington','Martin Luther King Jr.','Nelson Mandela',
  'Mahatma Gandhi','Madre Teresa de Calcutá','Princesa Diana','Rainha Elizabeth II',
  'Dalai Lama','Papa Francisco','Buda','Confúcio','Sócrates','Platão','Aristóteles',
  // Esportes (Lendas e Atuais Populares)
  'Pelé','Maradona','Lionel Messi','Cristiano Ronaldo','Neymar Jr.','Zico','Ronaldinho Gaúcho',
  'Ronaldo Fenômeno','Romário','Zidane','Beckham','Mbappé','Marta (Futebol)',
  'Michael Jordan','LeBron James','Kobe Bryant','Shaquille O\'Neal','Stephen Curry',
  'Magic Johnson','Larry Bird','Yao Ming','Usain Bolt','Michael Phelps',
  'Tiger Woods','Roger Federer','Rafael Nadal','Novak Djokovic','Serena Williams',
  'Venus Williams','Maria Sharapova','Lewis Hamilton','Ayrton Senna','Michael Schumacher',
  'Nelson Piquet','Emerson Fittipaldi','Simone Biles','Rebeca Andrade',
  'Gabriel Medina','Ítalo Ferreira','Tony Hawk','Rayssa Leal',
  'Mike Tyson','Muhammad Ali','Anderson Silva','Popó','Charles do Bronx',
  // Música (Ídolos Populares)
  'Michael Jackson','Elvis Presley','Freddie Mercury','Madonna','Beyoncé','Taylor Swift',
  'Lady Gaga','Rihanna','Ariana Grande','Justin Bieber','Bruno Mars','Ed Sheeran',
  'Adele','Billie Eilish','Bob Marley','John Lennon','Paul McCartney','Mick Jagger',
  'David Bowie','Prince','Whitney Houston','Britney Spears','Shakira','Jennifer Lopez',
  'Anitta','Ludmilla','Ivete Sangalo','Roberto Carlos','Erasmo Carlos','Rita Lee',
  'Cazuza','Renato Russo','Tim Maia','Jorge Ben Jor','Caetano Veloso','Gilberto Gil',
  'Chico Buarque','Elis Regina','Gal Costa','Maria Bethânia','Marília Mendonça',
  'Gusttavo Lima','Luan Santana','Zezé Di Camargo','Luciano','Leonardo',
  'Chitãozinho','Xororó','Luísa Sonza','Pabllo Vittar','Gloria Groove',
  // Cinema e TV (Atores e Personagens)
  'Marilyn Monroe','Audrey Hepburn','Elizabeth Taylor','Charlie Chaplin','James Dean',
  'Brad Pitt','Angelina Jolie','Leonardo DiCaprio','Johnny Depp','Tom Cruise',
  'Will Smith','Denzel Washington','Morgan Freeman','Samuel L. Jackson','Harrison Ford',
  'Arnold Schwarzenegger','Sylvester Stallone','Jackie Chan','Bruce Lee','Jet Li',
  'Robert Downey Jr.','Scarlett Johansson','Chris Hemsworth','Chris Evans','Mark Ruffalo',
  'Tom Holland','Zendaya','Meryl Streep','Julia Roberts','Anne Hathaway',
  'Jennifer Lawrence','Natalie Portman','Margot Robbie','Ryan Gosling','Cillian Murphy',
  'Pedro Pascal','Jenna Ortega','Millie Bobby Brown','Wagner Moura','Selton Mello',
  'Fernanda Montenegro','Lázaro Ramos','Taís Araújo','Alice Braga','Rodrigo Santoro',
  'Xuxa','Angélica','Eliana','Faustão','Silvio Santos','Luciano Huck','Ana Maria Braga',
  'Jô Soares','Gugu Liberato','Hebe Camargo','Marcos Mion','Tatá Werneck',
  // Personagens Icônicos (Ficcção)
  'Mickey Mouse','Pato Donald','Pateta','Pernalonga','Patolino','Tom e Jerry',
  'Snoopy','Garfield','Hello Kitty','Pikachu','Super Mario','Luigi','Sonic',
  'Batman','Superman','Mulher-Maravilha','Coringa','Homem-Aranha','Homem de Ferro',
  'Capitão América','Thor','Hulk','Pantera Negra','Viúva Negra','Doutor Estranho',
  'Harry Potter','Hermione Granger','Rony Weasley','Voldemort','Dumbledore',
  'Luke Skywalker','Darth Vader','Princesa Leia','Yoda','Han Solo','Chewbacca',
  'Indiana Jones','James Bond (007)','Lara Croft','Sherlock Holmes','Drácula',
  'Frankenstein','Lobisomem','Zumbi','Fantasma','Papai Noel','Coelho da Páscoa',
  'Fada do Dente','Peter Pan','Sininho','Cinderela','Branca de Neve','Ariel',
  'Bela (A Bela e a Fera)','Elsa (Frozen)','Anna (Frozen)','Olaf','Pinóquio',
  'Shrek','Burro (Shrek)','Fiona','Gato de Botas','Simba','Pumba','Timão',
  'Mufasa','Scar','Scooby-Doo','Salsicha','Velma','Fred','Daphne',
  'Bob Esponja','Patrick Estrela','Lula Molusco','Sr. Siriguejo','Sandy Bochechas',
  'Chaves','Quico','Chiquinha','Sr. Madruga','Dona Florinda','Prof. Girafales',
  'Bruxa do 71','Nhonho','Chapolin Colorado','Naruto','Goku','Vegeta',
  'Monkey D Luffy','Zoro','Ash Ketchum','Barbie','Ken','Optimus Prime',
  'Bumblebee','Wolverine','Deadpool','Jack Sparrow','Frodo Bolseiro',
  'Gandalf','Legolas','Gollum','Jon Snow','Daenerys Targaryen','Tyrion Lannister',
  'Walter White','Jesse Pinkman','Eleven (Stranger Things)','Wandinha Addams',
  'Homer Simpson','Bart Simpson','Lisa Simpson','Marge Simpson','Maggie Simpson',
  'Peter Griffin','Eric Cartman','Sr. Incrível','Mulher Elástica','Gelado',
  'Buzz Lightyear','Woody','Relâmpago McQueen','Mater','Wall-E',
  'Ratatouille (Remy)','Kung Fu Panda (Po)','Banguela (Dragão)',
  // Figuras Brasileiras Específicas
  'Dom Pedro I','Dom Pedro II','Princesa Isabel','Getúlio Vargas','JK',
  'Lula','Dilma Rousseff','Bolsonaro','Fernando Henrique Cardoso','Tancredo Neves',
  'Oscar Niemeyer','Cândido Portinari','Tarsila do Amaral','Machado de Assis',
  'Monteiro Lobato','Cecília Meireles','Clarice Lispector','Jorge Amado','Paulo Coelho',
  'Ziraldo','Maurício de Sousa','Mônica','Cebolinha','Cascão','Magali',
  'Bento Rinone','Galinha Pintadinha','Mundo Bita','Casimiro (Cazé)','Felipe Neto',
  'Whindersson Nunes','Juliette','Gil do Vigor','Virgínia Fonseca',
  // Profissões e Tipos (Persona)
  'Médico','Enfermeiro','Bombeiro','Policial','Professor','Cozinheiro',
  'Padeiro','Garçom','Motorista','Piloto de Avião','Astronauta','Cientista',
  'Pintor','Escultor','Músico','Cantor','Dançarino','Ator','Palhaço','Mágico',
  'Juiz','Advogado','Engenheiro','Arquiteto','Jardineiro','Agricultor',
  'Pescador','Lenhador','Mineiro','Marinheiro','Soldado','Fotógrafo',
  'Jornalista','Repórter','Youtuber','Influencer','Programador','Hacker',
  'Padre','Bispo','Pastor','Monge','Xamã','Pajé','Detetive','Espião',
  // Criaturas e Entidades
  'Lobisomem','Vampiro','Zumbi','Múmia','Sereia','Centauro','Minotauro',
  'Anjo','Demônio','Fantasma','Bruxa','Mago','Dragão','Unicórnio','Fênix',
  'Saci-pererê','Curupira','Caipora','Iara','Cuca','Mula sem Cabeça',
  'Bicho-Papão','Homem do Saco','Lúcifer','Cupido','Iemanjá',
  // Continuação Pessoas Gerais (Cultura Pop)
  'Billie Eilish','Dua Lipa','Post Malone','Drake','The Weeknd','Kendrick Lamar',
  'Kanye West','Travis Scott','Harry Styles','Zayn Malik','Liam Payne',
  'Niall Horan','Louis Tomlinson','Camila Cabello','Selena Gomez','Demi Lovato',
  'Miley Cyrus','Katy Perry','Pink','Avril Lavigne','Lana Del Rey','Lorde',
  'Sia','Olivia Rodrigo','Doja Cat','Nicki Minaj','Cardi B','Megan Thee Stallion',
  'Shawn Mendes','Camila Cabello','Rosalía','J Balvin','Bad Bunny','Maluma',
  'Karol G','Daddy Yankee','Don Omar','Eminem','Snoop Dogg','50 Cent',
  'Jay-Z','Dr. Dre','Ice Cube','Tupac Shakur','Notorious B.I.G.','Lil Wayne',
  'Travis Scott','A$AP Rocky','Tyler, The Creator','Frank Ocean','Childish Gambino',
  'Bruno Mars','Anderson .Paak','Silk Sonic','Lizzo','SZA','H.E.R.',
  // Atores Adicionais
  'Tom Hanks','Al Pacino','Robert De Niro','Denzel Washington','Nicolas Cage',
  'Keanu Reeves','Jason Statham','Vin Diesel','Dwayne Johnson (The Rock)','John Cena',
  'Ryan Reynolds','Chris Pratt','Benedict Cumberbatch','Tom Hardy','Jake Gyllenhaal',
  'Joaquin Phoenix','Christian Bale','Heath Ledger','Jared Leto','Will Ferrell',
  'Adam Sandler','Jim Carrey','Ben Stiller','Jack Black','Kevin Hart','The Rock',
  'Gal Gadot','Emma Watson','Jennifer Aniston','Courteney Cox','Lisa Kudrow',
  'Matt LeBlanc','Matthew Perry','David Schwimmer','Sofia Vergara','Kaley Cuoco',
  'Jim Parsons','Johnny Galecki','Simon Helberg','Kunal Nayyar','Melissa Rauch',
  'Mayim Bialik','Ellen DeGeneres','Jimmy Fallon','James Corden','Conan O\'Brien',
  'Oprah Winfrey','Kim Kardashian','Kylie Jenner','Kendall Jenner','Khloé Kardashian',
  'Kourtney Kardashian','Kris Jenner','Justin Timberlake','Zac Efron','Vanessa Hudgens',
  // Brasileiros Extras
  'Rodrigo Faro','Angélica','Eliana','Serginho Groisman','Ratinho','Celso Portiolli',
  'Sabrina Sato','Grazi Massafera','Cauã Reymond','Marina Ruy Barbosa','Bruna Marquezine',
  'Neymar','Gabriel Jesus','Vinícius Jr.','Rodrygo','Richarlison','Alisson Becker',
  'Tiago Leifert','Boninho','Tadeu Schmidt','Pedro Bial','William Bonner','Renata Vasconcellos',
  'Majú Coutinho','Sandra Annenberg','Evaristo Costa','Dudu Camargo','Marcão do Povo',
  'Datena','Marcelo Rezende (Saudoso)','Luiz Bacci','Jorge Kajuru','Silas Malafaia',
  'Edir Macedo','Valdemiro Santiago','Pe. Marcelo Rossi','Pe. Fábio de Melo',
  // Heróis e Vilões
  'Aquaman','Flash','Cyborg','Shazam','Gavião Arqueiro','Falcão','Soldado Invernal',
  'Loki','Thanos','Ultron','Kang','Magneto','Professor X','Ciclope','Jean Grey',
  'Tempestade','Vampira','Fera','Gambit','Noturno','Colossus','Psylocke',
  'Demolidor','Justiceiro','Jessica Jones','Luke Cage','Punho de Ferro',
  'Venom','Carnificina','Duende Verde','Doutor Octopus','Sandman','Mysterio',
  'Mulher-Gato','Pinguim','Charada','Duas-Caras','Bane','Espantalho','Arlequina',
  'Hera Venenosa','Ra\'s al Ghul','Lex Luthor','General Zod','Apocalipse (DC)',
  'Brainiac','Darkseid','Exterminador','Pacificador','Adão Negro',
  // Extras Diversos
  'Gisele Bündchen','Adriana Lima','Alessandra Ambrósio','Naomi Campbell','Tyra Banks',
  'Heidi Klum','Kate Moss','Vogue (Anna Wintour)','Giorgio Armani','Karl Lagerfeld',
  'Coco Chanel','Christian Dior','Gianni Versace','Donatella Versace','Ralph Lauren',
  'Calvin Klein','Tommy Hilfiger','Miuccia Prada','Guccio Gucci','Louis Vuitton',
  'Steve Wozniak','Linus Torvalds','Tim Berners-Lee','Vint Cerf','Robert Kahn',
  'Ada Lovelace','Grace Hopper','Margaret Hamilton','Katherine Johnson','Dorothy Vaughan',
  'Mary Jackson','Neil Armstrong','Buzz Aldrin','Yuri Gagarin','Valentina Tereshkova',
  'John Glenn','Chris Hadfield','Scott Kelly','Marcos Pontes','Almondega',
  'Zumbi dos Palmares','Tiradentes','Anita Garibaldi','Lampião','Maria Bonita',
  'Antônio Conselheiro','Padre Cícero','Frei Galvão','Irmã Dulce','Chico Xavier',
  // Atletas Brasil
  'Hortência','Magic Paula','Oscar Schmidt','Gustavo Kuerten (Guga)','Maria Esther Bueno',
  'Robert Scheidt','Torben Grael','Adhemar Ferreira da Silva','Joaquim Cruz','Maurren Maggi',
  'Thiago Braz','Arthur Zanetti','Diego Hypólito','Daniele Hypólito','Jade Barbosa',
  'Flávia Saraiva','Gabriel Medina','Ítalo Ferreira','Adriano de Souza','Filipe Toledo',
  'Marta','Formiga','Cristiane','Beatriz Haddad Maia','Hugo Calderano',
  // Mais Música Brasil
  'Péricles','Thiaguinho','Mumuzinho','Ferrugem','Dilsinho','Belo','Soweto','SPC',
  'Alexandre Pires','Raça Negra','Luiz Carlos','Molejo','Anderson Leonardo',
  'Zeca Pagodinho','Arlindo Cruz','Jorge Aragão','Beth Carvalho','Alcione',
  'Martinho da Vila','Paulinho da Viola','Xande de Pilares','Tie','Dudu Nobre',
  'Sorriso Maroto','Bruno Cardoso','Turma do Pagode','Pixote','Dodô',
  'Jeito Moleque','Inimigos da HP','Exaltasamba','Katinguelê','Salgadinho',
  'Negritude Jr','Netinho de Paula','Os Travessos','Rodriguinho','Art Popular',
  'Leandro Lehart','Kiloucura','Delcio Luiz','Negra Li','Racionais MC\'s','Mano Brown',
  'Emicida','Criolo','Projota','Rashid','Hungria Hip Hop','Tribo da Periferia',
  'Matuê','Teto','Wiu','L7nnon','Filipe Ret','Xamã','Poze do Rodo',
  'Orochi','Djonga','BK','Baco Exu do Blues','Flora Matos','Cynthia Luz',
  // Mais TV e Humor
  'Paulo Gustavo','Hassan','Whindersson','Tirullipa','GKAY','Carlinhos Maia',
  'Lucas Neto','Felipe Neto','RezendeEvil','AuthenticGames','Renato Garcia',
  'Enaldinho','Virginia','Zé Felipe','Bianca Andrade (Boca Rosa)','Jade Picon',
  'Arthur Aguiar','Naiara Azevedo','Karol Conká','Projota','Lucas Penteado',
  'Manu Gavassi','Rafa Kalimann','Thelma Assis','Babu Santana','Pyong Lee',
  // Personagens Infantis
  'Galinha Pintadinha','Galo Ataliba','Pintinho Amarelinho','Dona Aranha',
  'Sapo Cururu','Borboletinha','Bita','Dan','Lila','Tito','Flora',
  'Peppa Pig','George Pig','Papai Pig','Mamãe Pig','Patrulha Canina','Chase','Marshall',
  'Skye','Rubble','Rocky','Zuma','Everest','Tracker','Ryder',
  'Masha','Urso (Masha)','Dora a Aventureira','Botas','Baby Shark',
  'Bita (rep)','Luna (O Show da Luna)','Júpiter','Cláudio','Bolofofos','Rick','Pow',
  'Bunny','Pipi','Sophie','Totoy Kids','José Comilão','Sara',
  // Mitologia Pop
  'Zeus','Hera','Poseidon','Hades','Atenas','Ares','Afrodite','Apolo','Ártemis',
  'Hermes','Dionísio','Hebe','Hércules','Aquiles','Odisseu','Medusa','Pandora',
  'Thor','Odin','Loki','Freya','Heimdall','Tyr','Fenrir','Hel',
  'Anúbis','Osíris','Ísis','Hórus','Ra','Seth','Thoth','Bastet',
  // Clássicos Pessoas
  'Beethoven','Mozart','Bach','Vivaldi','Chopin','Tchaikovsky','Wagner','Verdi',
  'Puccini','Rossini','Strauss','Debussy','Ravel','Stravinsky','Gershwin',
  'Frank Sinatra','Tony Bennett','Dean Martin','Nat King Cole','Louis Armstrong',
  'Ella Fitzgerald','Billie Holiday','Nina Simone','Ray Charles','Aretha Franklin',
  'Stevie Wonder','Marvin Gaye','James Brown','Tina Turner','Diana Ross',
  'Cher','Barbra Streisand','Celine Dion','Mariah Carey','Liza Minnelli',
  // Atores/Atrizes Famosos
  'Sophia Loren','Marcello Mastroianni','Brigitte Bardot','Alain Delon','Jean Reno',
  'Vincent Cassel','Penélope Cruz','Antonio Banderas','Javier Bardem','Salma Hayek',
  'Benicio Del Toro','Andy Garcia','Viola Davis','Octavia Spencer','Taraji P. Henson',
  'Angela Bassett','Mahershala Ali','Daniel Kaluuya','John Boyega','Idris Elba',
  'Lupita Nyong\'o','Zoe Saldana','Michelle Yeoh','Jackie Chan (rep)','Gong Li',
  'Ken Watanabe','Hiroyuki Sanada','Dev Patel','Priyanka Chopra','Deepika Padukone',
];
export const PESSOAS_POP_TOTAL = 835; // ~835 items
